### ISSUE TITLE
[SI] Typo in stream definition of  Streaming Integrator 101

### ISSUE THREAD

**Issue by himasha** [wso2/docs-ei#1006]
**Description:**
In https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/quick-start-guide-101/ . step 3 refers to a property called 'deviceNo' which should be 'deviceID'.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
Corrected via [1].

[1] https://github.com/wso2/docs-ei/pull/1482
