### ISSUE TITLE
[ In Complete Docs ]  - Getting SI Running with MI in Five Minutes

### ISSUE THREAD

**Issue by Nirothipan** [wso2/docs-ei#1009]
**Description:**
The doc  [Getting SI Running with MI in Five Minutes](https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/hello-world-with-mi/) is incomplete and with broken steps.

- The siddhi app configuration needs to be updated.
- The URL to invoke needs to be updated.
- Few pieces of information about respond mediator and etc needs to be updated.

Please re-visit and update them. You may refer https://github.com/wso2/streaming-integrator/tree/master/modules/samples/artifacts/ConnectToMicroIntegratorFromSI

**Comment by Nirothipan** [comment]
> Please check the corrections done via [1].
> 
> [1] #1011

Added a comment, please check.

**Comment by RukshiW** [comment]
The comments in this thread as well as the related mail are addressed via [1].

[1] https://github.com/wso2/docs-ei/pull/1019

**Comment by RukshiW** [comment]
Please note that steps provided in the Triggering Integration Flows tutorial [1] still do not work. Please advise what needs to be changed.

[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/examples/triggering-integrations-via-micro-integrator/

**Comment by RukshiW** [comment]
There was a mismatch in the port mentioned in the Siddhi application and the port in the curl command. Also added instructions to install the required Siddhi extensions. Tested the tutorial after making the changes.
