### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by krishnilak** [wso2/docs-ei#1049]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/setup/installing-si-using-docker/

`docker pull wso2/streaming-integrator` command gives an error saying 
> Error response from daemon: manifest for wso2/streaming-integrator:latest not found
But following command works

`docker pull wso2/streaming-integrator:1.0.0`

If the latest version is not auto-detected you can mention it as <version>. 

Same applies to the below command as well

`docker run -it wso2/streaming-integrator`
Since the latest version is not detected, the above command gives an error whereas 
`docker run -it wso2/streaming-integrator/1.0.0` 
does not give any error

**Comment by RukshiW** [comment]
Corrected via [1].

[1] https://github.com/wso2/docs-ei/pull/1482
