### ISSUE TITLE
Doc Feedback: Gmail connector page not found

### ISSUE THREAD

**Issue by glaucioguerra** [wso2/docs-ei#1066]
Hi,
The page gmail connector (latest version of Integrator 7) is not found:
Location : https://ei.docs.wso2.com/en/latest/page-not-found/#importing-the-gmail-connector-into-wso2-integration-studio

**Comment by nilminiwso2** [comment]
Sorry about the late reply.
Is this link you are referring to? https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/using-the-gmail-connector/#importing-the-gmail-connector-into-wso2-integration-studio

**Comment by nilminiwso2** [comment]
Hope this is sorted now.
Please get back to us if there are any further issues.

**Comment by glaucioguerra** [comment]
Hi,
That's right! Thanks.
