### ISSUE TITLE
Direct links to ballerina central connectors not working

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-ei#1067]
**Description:**
From the connector page - https://ei.docs.wso2.com/en/latest/ballerina-integrator/references/ei-connectors/, clicking any connectors will get to page that says "the server was not able to find what you were looking for."

<img width="551" alt="Screen Shot 2020-01-08 at 12 07 39 PM" src="https://user-images.githubusercontent.com/57770159/72011828-7cec9880-320f-11ea-8972-e07c683b4e3b.png">
If you go to central.ballerina.io, browse and click the connectors, it shows up the page without an error.

**Comment by samgnaniah** [comment]
These links now work. However, we have also made some strategic changes to Ei 7.0.0 with regards to this integrator:

To provide a more focused enterprise integration experience to our customers and community, WSO2 has made a strategic decision on the composition of the WSO2 Enterprise Integrator 7 product suite. Ballerina Integrator, which is based on the Ballerina programming language, will no longer be a part of the WSO2 Enterprise Integrator.

Ballerina Integrator inherits its power from the Ballerina programming language. Therefore, moving Ballerina Integrator’s integration-related features to the programming language itself further enhances the user experience.

WSO2 continues its commitment to Ballerina and the development of Ballerina-based products, and it will happen outside the WSO2 Enterprise Integrator brand.

With this change, we have released WSO2 Enterprise Integrator 7.0.2.

If you have any further questions, please feel free to contact us as http://wso2.com/contact/
