### ISSUE TITLE
EI 7 latest documentation lists Oracle JDK as a requirement - can we change this to OpenJDK?

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-ei#1068]
**Description:**
EI docs list Oracle JDK as a requirement. Is it possible to change this to OpenJDK? I tested couple of samples (not an exhaustive test) with OpenJDK and it's working without any issues.

It shouldn't be an issue because ballerina ships with OpenJDK.

**Comment by nilminiwso2** [comment]
Hi, could you check the latest documentation for EI 7.1.0.
EI 7.1.0 is tested s tested with OpenJDK.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/install_prerequisites/#tested-environments
