### ISSUE TITLE
The documentation for encrypting passwords in docker needs to be updated

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/docs-ei#1070]
**Steps to Follow:**

Document to follow: https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/

1. Download micro integrator zip
2. Run cipher tool (./ciphertool.sh -Dconfigure)
3. Create a folder called "dockerProject" to keep the docker project.
4. Then,
    Copy <MI_HOME>/conf/security/secret-conf.properties file to the dockerProject folder
    Copy <MI_HOME>/conf/security/cipher-tool.properties file to the dockerProject folder

5. Update following entry in file secret-conf.properties copied in above step
    keystore.identity.location=/home/wso2carbon/wso2mi-1.1.0/repository/resources/security/wso2carbon.jks

6. Create a file named "password-tmp" in dokcerProject folder. Add key store password in plain text in that file. After the container is started
this file will get deleted automatically.

7. Add some vault entries to micro integrator zip running the script securevault.sh (please refer wso2 doc)
8. When done, copy <MI_HOME>/registry/config/repository/components/secure-vault/secure-vault.properties file to the docker project
9. Copy probe car file to the docker project
10. Copy test car file to the docker project

11. Write the docker file (attached) in the same docker project folder (note the flag --chown=wso2carbon:wso2)

12. create a new docker image from the dokcer file
13. run it using docker

Dockerfile to be used: [Dockerfile.txt](https://github.com/wso2/docs-ei/files/4039488/Dockerfile.txt)

**Comment by nilminiwso2** [comment]
The instructions for this process has changed. This is documented for the EI 7.1.0 release by [1].

[1] https://github.com/wso2/docs-ei/pull/1548
