### ISSUE TITLE
Doc Feedback: incorrect instructions

### ISSUE THREAD

**Issue by Terline** [wso2/docs-ei#1073]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/creating_keystores/

In paragraph **Creating a keystore using an existing certificate,** there are command examples to perform 2 different tasks. Yet both commands are identical:
-  **export certificates to the PKCS12/PFX format** 
     `openssl pkcs12 -export -in <certificate file>.crt -inkey <private>.key -name "<alias>" -certfile <additional certificate file> -out <pfx keystore name>.pfx`
- **Convert the PKCS12/PFX formatted keystore to a Java keystore** 
     `openssl pkcs12 -export -in <certificate file>.crt -inkey <private>.key -name "<alias>" -certfile <additional certificate file> -out <pfx keystore name>.pfx`

Could you fix this and provide the proper command example to convert the PKCS12/PFX keystore to a Java keystore ?

Thank you!

**Comment by nilminiwso2** [comment]
Please check this updated doc: https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/creating_keystores/

**Comment by nilminiwso2** [comment]
Fixed.
Thanks for reporting.

**Comment by Terline** [comment]
Thank you for fixing!
