### ISSUE TITLE
[Doc] Steps to disabling lazy initialization for user management configurations

### ISSUE THREAD

**Issue by milindaperera** [wso2/docs-ei#1087]
**Description:**
As introduced with wso2/micro-integrator#849 by default the user management configurations are loaded on demand. We need to add steps to disable it if some user to perform eager initialization.

Configuration:
Default: Enabled
System property ”mi.security.usermgt.lazy.init” should be set to “false” to disable or enable eager initialization of

**Comment by nilminiwso2** [comment]
fixed by https://github.com/wso2/docs-ei/pull/1201
