### ISSUE TITLE
[Uninstalling MI][macos] Doc should be corrected

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1090]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/install_in_vm/

The command to uninstall in macOS should be updated as follow. 
`sudo bash /Library/WSO2/EnterpriseIntegrator/7.0.1/uninstall.sh 
`

**Comment by nilminiwso2** [comment]
Fixed.
Since the current version is 7.0.2, the following URL was used: sudo bash /Library/WSO2/EnterpriseIntegrator/7.0.2/uninstall.sh

[1] https://github.com/wso2/docs-ei/pull/1474/files
