### ISSUE TITLE
Doc Feedback: Typos, screenshot order  and missing screens

### ISSUE THREAD

**Issue by robbla** [wso2/docs-ei#1092]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/develop/create-docker-project/

The page has some issues like: 

This project directory allows you to package multiple integration projects (created as ESB **pojects**) into a single Docker image and then build and push to the Docker registries

Info

If you already have an ESB Config project with the integration artifacts, click Miscellaneous → Create New Docker/Kubernetes Project in the Getting Started view as shown below.  Only two screenshots, could be enhanced.

Point 3 Enter information in the Docker/Kubernetes Project Information page as follows: image shows other fieldnames

**Comment by nilminiwso2** [comment]
Fixed.
This content is now revamped along with some significant updates to the tool.
Thanks for reporting!

- https://ei.docs.wso2.com/en/latest/micro-integrator/develop/create-docker-project/
- https://ei.docs.wso2.com/en/latest/micro-integrator/develop/create-kubernetes-project/
- https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-project-solution/
