### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by sandeepparbat** [wso2/docs-ei#1094]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/overview/introduction/

Hi Team,

Please provide pdf documentation file as it is more comfortable to read.
Document of API Manager 3.0.0 and Micro Integrator 7.0.0 and Streaming Intregator 7.0.0

Thanks
Sandeep Parbat

**Comment by nilminiwso2** [comment]
Thank you for the feedback.
We are currently looking into this.

**Comment by nilminiwso2** [comment]
This requirement will be tracked through https://github.com/wso2/docs-ei/issues/439
