### ISSUE TITLE
Issue in Prometheus for Monitoring document

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/docs-ei#1102]
@orifux commented on [Sun Feb 09 2020](https://github.com/wso2/micro-integrator/issues/1131)

**Description:**
Following doc  https://ei.docs.wso2.com/en/next/micro-integrator/administer-and-observe/monitoring_with_prometheus/
the - targets parameter should be set to port 9191 in prometheus.yml file. But when I checked the target state in prometheus (http://localhost:9090/targets)  it was "down" and there was an error message "connection refused".
After I set the - targets parameter to 9201 it worked fine. 
 
**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
micro-integrator 7.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

---

@sdkottegoda commented on [Mon Feb 10 2020](https://github.com/wso2/micro-integrator/issues/1131#issuecomment-583960197)

Thank you for reporting this issue. We will correct the documentation accordingly.

**Comment by nilminiwso2** [comment]
Fixed.
Thanks for reporting!
