### ISSUE TITLE
Doc Feedback: 6.5.0 mentioned rather than 6.6.0 

### ISSUE THREAD

**Issue by robbla** [wso2/docs-ei#1161]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/using-the-analytics-dashboard/

Starting the Analytics Worker¶

Note

Be sure to start the Analytics worker before starting the Micro Integrator.

    Download and install WSO2 Enterprise Integrator **6.5.0**. The location of your WSO2 EI 6.5.0 installation will be referred to as <EI_6.5.0_HOME> from hereon.
    Open a terminal and navigate to the <EI_6.5.0_HOME>/wso2/analytics/bin directory.

and typo
To allow the Micro Integrator server and the Analytics server to communicate using SSL, the digital **certifacates** should be shared by the two servers. See the instructions on adding SSL certificates to keystores.

**Comment by nilminiwso2** [comment]
Fixed the typo.
Thanks for reporting.

Note that we have kept we are generally referring to the EI 6.x.x Analytics profile. However, the links lead to the latest release of the EI 6.x.x family (which is EI 6.6.0).
