### ISSUE TITLE
Incorrect Parameter in scheduled task tutorial

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#1231]
**Description:**
There is an incorrect parameter value in the [scheduled task tutorial](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/using-scheduled-tasks/).

In the **Creating the Scheduled Task** section, when editing **Task Implementation Properties** (step 4), following value should be corrected.
Given value: **injectTo**: `InjectXMLTask` 
Correct value: **injectTo**: `sequence`

**Comment by nilminiwso2** [comment]
Fixed.

**Comment by nilminiwso2** [comment]
- https://github.com/wso2/docs-ei/pull/1476
- https://github.com/wso2/docs-ei/pull/1477
