### ISSUE TITLE
Doc Feedback: Streaming Integrator Tooling

### ISSUE THREAD

**Issue by vraghu1983** [wso2/docs-ei#1253]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/quick-start-guide-101/
Went to the GitHub link for this and then tried to do a mvc clean install for Streaming Integrator Tooling component as I need to do a Siddhi app. 

However, facing this error. 
Can someone please let me know the correct way to do this etc.. 
![Screenshot - 24-03-2020 , 13_41_11](https://user-images.githubusercontent.com/11383924/77405431-33a4f180-6dd9-11ea-9921-12b208edc582.png)

**Comment by RukshiW** [comment]
Moved this to the Streaming Integrator Tooling repository because it is not a documentation issue, but a question about how to build the tooling package.
