### ISSUE TITLE
No direct link to download Integration Studio on website

### ISSUE THREAD

**Issue by mifanc** [wso2/docs-ei#1271]
**Description:**
On the WSO2.com website, no direct way of downloading Integration Studio

**Suggested Labels:**
Website

**Suggested Assignees:**
Thimuth, Amal

**Affected Product Version:**
EI 7.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Try to access Integration-Studio downloads from wso2.com integration page: https://wso2.com/integration/

**Related Issues:**

**Comment by rymonteiro** [comment]
You have to go directly to Micro-Integrator

https://wso2.com/integration/micro-integrator/

**Comment by nilminiwso2** [comment]
The link is now added to the main page as well. Hence, will close this issue.
![Screen Shot 2020-06-16 at 9 43 29 AM](https://user-images.githubusercontent.com/21237558/84731226-dd011b00-afb5-11ea-9dfa-d331d7fe677f.png)

Thanks for reporting!
