### ISSUE TITLE
HTTP to MSMQ Example does not work

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#1292]
**Description:**

Example : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/protocol-switching/switching_between_HTTP_and_MSMQ/

1.  When running this example, First I got the following error : 
     `error reading from uri http://localhost:9000/services/SimpleStockQuoteService?wsdl`
2. The proxy tries to access a resource in `http://localhost:9000/services/SimpleStockQuoteService?wsdl`. But this resource is not exposed by the SimpleStockQuoteService given in the [documentation](https://github.com/wso2-docs/WSO2_EI/blob/master/Back-End-Service/stockquote_service.jar). 
3. The Sample `SimpleStockQuoteService` packed with EI 6.6.0 does expose the WSDL resource so I set it up following this [doc](https://docs.wso2.com/display/EI660/Setting+Up+the+ESB+Samples). Now I there are no errors when running the broker.
4.  But when the proxy is invoked using the axis2client in the sample of EI 6.6.0 with the following command, expected outcomes are not delivered.
 `ant stockquote -Daddurl=http://localhost:8280/services/StockQuoteProxy -Dmode=placeorder -Dsymbol=MSFT`

**Expected:** 
In the axis2Server: `Accepted order for : 18406 stocks of MSFT at $ 83.58806051152119`

**Observed:**
 No output in the axis2Server.
In the broker: `The engine will expire all callbacks after GLOBAL_TIMEOUT`

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/848

**Comment by Nirothipan** [comment]
@SanojPunchihewa will be working on this

**Comment by SanojPunchihewa** [comment]
This issue will be put on hold

**Comment by chanikag** [comment]
https://github.com/wso2/docs-mi/issues/664 will be used to track this
