### ISSUE TITLE
Need an email with valid authentication details

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#1302]
**Description:**
When running this [example](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/file-processing/mailto-transport-examples/), micro integrator throws the following error.

`[2020-03-31 14:11:50,845] ERROR {org.apache.axis2.transport.mail.MailTransportListener} - Error connecting to mail server for address : synapse.demo.1@gmail.com :: [AUTH] Username and password not accepted. javax.mail.AuthenticationFailedException: [AUTH] Username and password not accepted.`

When I updated the mail and password in the synapse configuration with my personal email it works. However, running the example with personal email is not appropriate as the broker will start to process and respond to all the spam mails as well. It is better to give access to the given email.

**Steps to reproduce:**
Follow this [example](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/file-processing/mailto-transport-examples/).

**Related Issues:** https://github.com/wso2/devstudio-tooling-ei/issues/860

**Comment by Nirothipan** [comment]
Since the details need to be publicly available in the docs, its not a good idea to provide a mail account there. User can update their personal mail details for this purpose as mentioned in the note or if processing spam is an issue, they might use a separate one.
