### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by vipin-nirwal** [wso2/docs-ei#1418]
Location : https://ei.docs.wso2.com/en/next/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/

I am not able to reach at given location to download monitoring dsahboard.
 WSO2 Micro Integrator website -> Download -> Other Resources, and click Monitoring Dashboard

**Comment by nilminiwso2** [comment]
This is resolved now.
Do let us know if you run into further issues.
