### ISSUE TITLE
Incorrect access log pattern in EI 6.1.1 documentation

### ISSUE THREAD

**Issue by Ashan23Perera** [wso2/docs-ei#1438]
**Description:**
As per the documentation [1]  %T can be used to capture "Time taken to process the request in seconds". However, after adding %T to the log pattern, it is logging Content-Type instead of the time taken. It should be rectified as shown in documentation [2].

**Suggested Labels:** Docs

**Affected Product Version:** EI 6.1.1

[1]. https://docs.wso2.com/display/EI611/Monitoring+ESB+Access+Logs
[2]. https://docs.wso2.com/display/ESB490/Access+Logs

**Comment by nilminiwso2** [comment]
Fixed from EI 6.1.1 to EI 6.6.0.

[1] https://docs.wso2.com/display/EI660/Monitoring+Access+Logs
