### ISSUE TITLE
EI-6.6.0 Update the Oracle RAC resources 

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-ei#1471]
**Description:**
This is created to update the Oracle RAC resources [1] along with the fixes done in [2]. Details such as using the "-Dsetup" option (which is depricated) should be revisited. 

[1]. https://docs.wso2.com/display/EI660/Setting+up+Oracle+RAC+
[2]. https://github.com/wso2/product-ei/issues/5050

**Affected Product Version:**
EI-6.6.0 

**OS, DB, other environment details and versions:**    
Oracle 19C RAC

**Related Issues:**
https://github.com/wso2/product-ei/issues/5050

**Comment by chanikag** [comment]
Not related to MI docs
