### ISSUE TITLE
Docker image name MUST be fixed in the latest EI Docker documentation

### ISSUE THREAD

**Issue by dunithd** [wso2/docs-ei#1493]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/run_in_docker/

When pulling MI Docker image from WSO2 Docker registry, the image name should be correct as follows.

Change
`docker.wso2.com/micro-integrator:1.1.0`

To
`docker.wso2.com/wso2mi `

Otherwise the below error will be displayed.
`Error response from daemon: manifest for docker.wso2.com/micro-integrator:1.1.0 not found: manifest unknown: manifest unknown`

**Comment by nilminiwso2** [comment]
Fixed! 
Thanks for reporting.
