### ISSUE TITLE
[Tooling] Update docs with newly added maven profiles

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#1497]
**Description:**
Maven profiles are added to the maven multi module projects to facilitate building only a subset of modules at a time. Docs should be updated accordingly.

**Related Issues:** https://github.com/wso2/devstudio-tooling-ei/issues/888

**Comment by nilminiwso2** [comment]
Content already added.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/create-integration-project/#building-selected-mmm-profiles
