### ISSUE TITLE
'Salesforce Access Token Generation' doc does not mention where to create the account

### ISSUE THREAD

**Issue by dinuish94** [wso2/docs-ei#1508]
**Description:**
'Salesforce Access Token Generation' [1] doc does not clearly mention where to create the Developer account.

It should be created at https://developer.salesforce.com/signup instead of https://login.salesforce.com/?locale=eu

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/salesforce-rest-connector/sf-access-token-generation/

**Comment by samgnaniah** [comment]
This is fixed in 7.0.0 and master.
