### ISSUE TITLE
Connecting to ActiveMQ doc only has transport option

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-ei#1510]
**Description:**

When describing "connecting to ActiveMQ", we have this doc.

[https://ei.docs.wso2.com/en/latest/micro-integrator/setup/brokers/configure-with-
ActiveMQ/#setting-up-the-micro-integrator-with-activemq](https://ei.docs.wso2.com/en/latest/micro-integrator/setup/brokers/configure-with-
ActiveMQ/#setting-up-the-micro-integrator-with-activemq)

but it only describes the transport. We have the inbound option too. We need to re-structure the doc mentioning all options. 

Issue is, if someone need to point a doc stating, this is how you need to setup WSO2 EI with ActiveMQ, we cannot point this doc. It does not have all the options.

**Comment by chanikag** [comment]
This is the setup guide, which needs transport level config changes. However, these contents will be removed with the effort https://github.com/wso2/micro-integrator/issues/3592
