### ISSUE TITLE
Modify all doc samples to use call mediator instead of send mediator

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-ei#1511]
**Description:**

Go though all the documentation pages and update the samples. 

* Use <call/> instead of <send/>
* Instead of using proxy services, demonstrate the example using APIs. This is to go inline with API led integration platform concept. Anyways, SOAP technologies are relatively old and APIs is the trend. Most people will look for restful integration examples.

**Comment by isudana** [comment]
Having more samples for REST scenarios is useful, IMO we don't need to remove or replace existing SOAP proxy samples. 
Send mediator is a perfectly valid mediator to be used to send a request out from Synapse. 
Until we decide to deprecate it, we don't need to remove it from samples.

**Comment by abeykoon** [comment]
@isudana I agree with the point that there is not harm keeping the send mediator in the samples. However, the point is, our recommendation is the `call` mediator and what we have in samples is the `send` mediator. I think that's the contradiction we need to address. Developers may start copying the sample and edit as they need. If we have the `call` mediator in place, it goes with our encouragement to use the call mediator.

**Comment by abeykoon** [comment]
We'll keep a note and do this at APIM4 doc space in long run.
