### ISSUE TITLE
Incorrect EI Analytics 6.6.0 HA Configuration ServerURL 

### ISSUE THREAD

**Issue by ug205** [wso2/docs-ei#1512]
**Description:**

When configuring EI-Analytics nodes in a minimum high availability setup, we need to add the 'ServerURL' in the carbon.xml file of the EI-server side as below in EI 6.6.0 version.

<ServerURL>tcp://analytics-server-1:7612|tcp://analytics-server-2:7612</ServerURL>

In the documentation [1] under 'Configuring the ESB to publish data to the Analytics profile', it is mentioned as below

> 'When you deploy EI Analytics as an HA cluster, enter the URLs of the Analytics nodes as a list of comma-separated URLs'

And the example is given as:
 _HA Cluster: tcp://analytics-server-1:7612,tcp://analytics-server-2:7612_

We need to correct this and mention that the URLs should be separated by the vertical bar (|) and change the example as well.

**Affected Product Version:**
EI-6.6.0 
EI-Analytics-6.6.0

[1].   https://docs.wso2.com/display/EI660/Publishing+ESB+Data+to+Analytics

**Comment by RukshiW** [comment]
Corrected as specified in the description.
