### ISSUE TITLE
Add Screenshots on Prometheus integration

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-ei#1518]
**Description:**

Add a few screenshots of prometheus integration which will give user an idea on what to get;
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/monitoring_with_prometheus/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
7.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
We now have a new Observability solution with Prometheus.
The current page on 'Prometheus' will be redirected to [1].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/observability/observability-deployment-strategy/

**Comment by nilminiwso2** [comment]
PR: https://github.com/wso2/docs-ei/pull/2304
