### ISSUE TITLE
Doc Feedback: Wording

### ISSUE THREAD

**Issue by eliehaykal** [wso2/docs-ei#1546]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/getting-started/create-the-siddhi-application/

Fix wording:
Before: The details to be captures include the room ID,
After: The details to be captured include the room ID,

**Comment by RukshiW** [comment]
This is addressed via [1].

[1] https://github.com/wso2/docs-ei/pull/1618
