### ISSUE TITLE
[Cluster Coordination Database] Include which database script needs to run

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1574]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/deployment/databases/setting-up-MSSQL/
We need to include that it needs to create the database and which script needs to run to create tables before starting the server.

**Comment by nilminiwso2** [comment]
information about the scripts are added in the latest docs:

- https://ei.docs.wso2.com/en/latest/micro-integrator/setup/databases/setting-up-MySQL/

Please reopen if you find any other issues.
