### ISSUE TITLE
Injecting params from a file is missing in MI doc space

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-ei#1584]
I see In EI 6.x docs we have a doc regarding how to inject parameters using a file. 
https://docs.wso2.com/display/EI6xx/Injecting+Parameters+using+a+file 

I suppose MI also support the same feature. It is useful for VM deployments. Please check and add it to MI doc space as well

**Comment by nilminiwso2** [comment]
Fixed. Added to the next doc release [1].

[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/injecting-parameters/
