### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by Methma** [wso2/docs-ei#1607]
**Description:**
Formatting issues in doc [1] 'Purpose section. Please reformat the doc.

[1]. https://ei.docs.wso2.com/en/7.1.0/streaming-integrator/samples/ReceivePrometheusMetrics/

**Suggested Labels:**
SI

**Affected Product Version:**
EI 7.1.0

**Comment by RukshiW** [comment]
Corrected the formatting issue mentioned.
