### ISSUE TITLE
[Doc] Refactor installation guide 

### ISSUE THREAD

**Issue by milindaperera** [wso2/docs-ei#1619]
**Description:**
Refactor installation guide[1]. Need to build completely. basically nothing out there.
Installation guide should contain proper recommended way to install for proper functionality for all major operating system flavours (Windows, Linux, MacOS) with screenshots

These installation would be familiar for majority. But installation guide must address for all the spectrum of audience. That's is the pattern followed by the all most all the software vendors.
If someone has to look / search for some other site/forum/blog to find how to do it, then documentation is no good.

When refactoring please do take mind to give instructions to a person who is using eclipse or IDE for his first time in life !

[1] https://docs.wso2.com/display/EI660/Installing+WSO2+Integration+Studio+

**Comment by gokkep** [comment]
I agree, I have exact the same issue with this. I currently am not able to set this up. Much documentation seems to refer older versions. Also it seems the WSO2 Integration Studio is kind of new product. The only thing I now want to do is build and debug a sample application https://github.com/wso2/samples-is/tree/master/sso-samples/saml2-sso-sample and I assume this could be done with this integration tool. But I really do not know how. Note, I do not come from a Java Eclipse world so I need extra guidance here.

**Comment by chanikag** [comment]
This is fixed in MI docs https://mi.docs.wso2.com/en/latest/install-and-setup/install/installing-mi/
