### ISSUE TITLE
Document on listing services deployed on Embedded MI

### ISSUE THREAD

**Issue by prabushi** [wso2/docs-ei#1622]
**Description:**
Need to add documentation on the implementation done with [this](https://github.com/wso2/devstudio-tooling-ei/issues/884).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/884

**Comment by nilminiwso2** [comment]
Content is already added to [1] as well as the tutorials.
Screenshot error will be fixed through issue [2].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/using-embedded-micro-integrator/#view-deployed-endpoints-in-the-embedded-server
[2] https://github.com/wso2/docs-ei/issues/2128
