### ISSUE TITLE
Doc Feedback: Docker image doesn't have bash

### ISSUE THREAD

**Issue by pedroruizaf** [wso2/docs-ei#1630]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/setup/installing-si-using-docker/

Running the docker image works but I cannot bash into the container to review configurations.

Running the command
`docker exec -it integrator bash`

Returns the following error message
`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

**Comment by senthuran16** [comment]
Hi @pedroruizaf ,
Please use `sh` instead of `bash`:
```
docker exec -it integrator sh
```
