### ISSUE TITLE
ConversionPattern pattern for logs 

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-ei#1637]
**Description:**
The following conversion pattern in the document [1] related to Enabling Logs for Services is incorrect (i.e: hostname or IP address are not logged) and therefore needs to be corrected. 

`log4j.appender.SQ_PROXY_APPENDER.layout.ConversionPattern=%d{ISO8601} \[%X{ip}-%X{host}\] \[%t\] %5p %c{1} %m%n`

[1]. https://docs.wso2.com/display/EI640/Enabling+Logs+for+Services

**Affected Product Version:**
EI-6.4.0

**Comment by chanikag** [comment]
Not there in the MI docs
