### ISSUE TITLE
Stupid documentation

### ISSUE THREAD

**Issue by OktaRiveranda** [wso2/docs-ei#1639]
Location : https://ei.docs.wso2.com/en/7.1.0/streaming-integrator/samples/PublishKafkaInAvroFormatUsingSchemaRegistry/

In the documentation saying that we need to add avro schema into schema registry via curl to some URl that is not mentioned earlier where it is located/ how it is installed in the first place. 

Post the avro schema to schema registry using, curl -X POST -H "Content-Type: application/json" --data '{ "schema": "{ \"type\": \"record\", \"name\": \"sweetProduction\",\"namespace\": \"sweetProduction\", \"fields\":[{ \"name\": \"name\", \"type\": \"string\" },{ \"name\": \"amount\", \"type\": \"double\" }]}"}' **_http://localhost:8081/subjects/sweet-production/versions_**

**Comment by RukshiW** [comment]
Did the following:

- Added descriptions to explain how the Avro schema is applied together with a link to Avro extension documentation in Siddhi documentation.

- Formatted the sample page to make it more usable.
