### ISSUE TITLE
Update ManagementAPI related docs to comply with the default behavior

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-ei#1642]
**Description:**
The ManagementAPI has been enabled by default in the MI server from MI-1.2.0 beta release onwards. We need to modify the related docs to comply with this default behavior.

**Related PRs:**
https://github.com/wso2/micro-integrator/pull/1638

**Comment by nilminiwso2** [comment]
Fixed in EI 7.1.0:

- https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/using-the-command-line-interface/
