### ISSUE TITLE
Update documentation on the required maven version for Docker build

### ISSUE THREAD

**Issue by prabushi** [wso2/docs-ei#1651]
**Description:**
With the new Spotify plugin version upgrade in docker and kubernetes projects, we need to have Maven >= 3.5.2 to build those projects. We need to update the documentation accordingly.

[1] https://awesomeopensource.com/project/spotify/dockerfile-maven

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 7.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed with [1].

[1] https://github.com/wso2/docs-ei/pull/2189
