### ISSUE TITLE
When using Using Docker Secrets we need to Initialize Secret Repository

### ISSUE THREAD

**Issue by malakaganga** [wso2/docs-ei#1652]
**Description:**
In doc https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/creating-artifacts/using_docker_secrets/#using-docker-secrets

We need to mention prior to use wso2:vault-lookup('<alias>', '<type>', 'true') (inEncrypted true)
we need to initialize the secret repository by using toolin.

**Comment by nilminiwso2** [comment]
Fixed by https://github.com/wso2/docs-ei/pull/1793

**Comment by nilminiwso2** [comment]
Done:
[1] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/using_docker_secrets/
