### ISSUE TITLE
Change doc build sequence

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#1657]
**Description:**
Currently, even if the doc build fails (according to Jenkins) due to a commit, the changes in the commit are published. This causes the docs site to go down.

**Suggested Labels:**
Build 

**Affected Product Version:**
Git docs

**Comment by Nirothipan** [comment]
Added a method to grep errors and fail  build based on it. Only parse errors are taken into action now.
```bash
error="MkDocs encountered as error parsing the configuration file"
```
If we encounter more errors in future , we need to add them to error logs.

```bash 
error="MkDocs encountered as error parsing the configuration file"

checkErrors(){

 if grep -q "$error"  $1;
  then
    echo "Errors in the build ... Marking the build as failure the artifacts won't be pushed to live site!!!!";
    exit 1;
  else
    echo "No errors while building the current docs. The artifacts will be pushed live !!!"; 
 fi
}
```
