### ISSUE TITLE
MI - INSTALL AND SETUP section (Deployment Synchronization)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#166]
Complete the docs on deployment synchronization [1].

[1] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/setup/deployment_synchronization.md

**Comment by nilminiwso2** [comment]
Done.
Need review.

**Comment by a5anka** [comment]
@nilminiwso2 we do not support dep sync in Micro Integrator. Therefore shall we remove [setup/deployment_synchronization.md](https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/setup/deployment_synchronization.md)?

**Comment by nilminiwso2** [comment]
Removed references to deployment synchronization from deployment docs.
