### ISSUE TITLE
Add documentation on AI based data mapper functionality

### ISSUE THREAD

**Issue by prabushi** [wso2/docs-ei#1660]
**Description:**

- Add documentation on the AI-based data mapper functionality including a concise real-world example.

- Add a clarification on how the user data is being sent, processed, and used to generate mapping on the remote service hosted in WSO2 cloud. (User data is sent securely and it will not be stored after processing)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed by:

- https://github.com/wso2/docs-ei/pull/2407
- https://github.com/wso2/docs-ei/pull/2408
