### ISSUE TITLE
Getting Started page going blank after loading

### ISSUE THREAD

**Issue by arunans23** [wso2/docs-ei#1676]
**Description:**

Getting started page seems to be going blank after sometime. But, when you move around the cursor, you can see that the buttons are still there (The click hand shows up. You can click as well).

**Affected Product Version:**
Integration Studio 7.1.0-Alpha

**OS, DB, other environment details and versions:**
Ubuntu 18.04, Firefox 59.0

**Comment by nilminiwso2** [comment]
Do we still have this issue for the GA version?

If so, we will add the following to the docs?

- This issue is only for Firefox users.
- And the issue is solved after upgrading to 77.0.1 version or above.

@arunans23 / @prabushi - Please confirm
