### ISSUE TITLE
Issues in Applying Security to a REST API Doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1690]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-an-api/

For the time being remove the following content from the doc as the steps seem to be not much clear and not explained well. 
Please reverify the content and add them back to the doc. 

- Using Kerberos to secure the REST API
- Using an OAuth base security token
- Using a policy file to authenticate with a secured back-end service

**Comment by Nirothipan** [comment]
Hi @isuruuy429, In this section, the focus was to how to create a data service and data source. Complete examples are linked in is section. Example: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/data_integration/rdbms-data-service/ with db scripts. Hence closing this.
