### ISSUE TITLE
[Integration Studio]Specify the program argument to view legacy properties view

### ISSUE THREAD

**Issue by Drifftr** [wso2/docs-ei#1698]
**Description:**
New program argument has been introduced to show legacy properties view(Table based) instead of the new group based view.

For this we have to add the following argument in IntegrationStudio.ini

`-Dorg.wso2.developerstudio.properties.legacy`

Issue - https://github.com/wso2/devstudio-tooling-ei/issues/1128

**Comment by nilminiwso2** [comment]
As discussed with the team, this issue will not be documented.
- The fix is no longer working.

Please reopen if there any changes.
