### ISSUE TITLE
Doc issue on the following page

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/docs-ei#1716]
**Description:**
Please find the below doc issues in the following MI documentation
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/monitoring_with_prometheus/

1. Instructions on the document is not complete, the document should point to end to end configuration of EI and Prometheus similar to what is done by API M team
https://docs.wso2.com/display/MG310/Observability
2.  metrics_path: "metric-service/metrics" should refer to  metrics_path: "/metric-service/metrics"
3. documentation is on how to run things on docker hence - targets: ['localhost:9201'] should not contain localhost but the default docker ip address 172.17.0.2

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MI 7.x
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
We now have a new Observability solution with Prometheus.
The current page on 'Prometheus' will be redirected to [1].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/observability/observability-deployment-strategy/

**Comment by nilminiwso2** [comment]
PR: https://github.com/wso2/docs-ei/pull/2304
