### ISSUE TITLE
[Creating a Data Service] Include a script to create a relevant database in the example. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1725]
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/creating-artifacts/data-services/creating-data-services/

As per the example in the doc, this is connected to an Employee database. It is better if we can add some steps to create a MySQL database as Employee with the given scripts before the 'Create the data service artifact' section.

**Comment by Nirothipan** [comment]
Hi @isuruuy429, In this section, the focus was to how to create a data service and data source. Complete examples are linked in is section. Example: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/data_integration/rdbms-data-service/ with db scripts. Hence closing this.
