### ISSUE TITLE
RabbitMQ documenation

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#1741]
Require new samples and content for the Rabbit MQ use case in EI 7.1.0.

- https://docs.google.com/document/d/1PLx4BdwWb9AUt6682k5biSHz6F1CM4eCMJ0NPHTBrvw/edithttps://docs.google.com/document/d/1PLx4BdwWb9AUt6682k5biSHz6F1CM4eCMJ0NPHTBrvw/edit

**Comment by lkokila** [comment]
1. The following properties are required to be explained in the RabbitMQ Inbound documentation [1]. These are already explained in the EI document [2]. 

rabbitmq.exchange.autodeclare
rabbitmq.queue.autodeclare 

2. In the MI-1.2.0 release, a new property called "SET_REQUEUE_ON_ROLLBACK" will be included. If this property is set to true in the fault sequence, the consumer (MI Inbound) will do a basicReject with the requeue flag set to true. So the RabbitMQ will redeliver the rejected messages immediately back to the consumer again. This needs to be documented along with the "SET_ROLLBACK_ONLY" in the MI-1.2.0 release documents. 

[1]. https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/

[2]. https://docs.wso2.com/display/EI650/RabbitMQ+AMQP+Transport

**Comment by nilminiwso2** [comment]
The following two properties are documented:
- rabbitmq.exchange.autodeclare
- rabbitmq.queue.autodeclare

In rabbitMQ transport properties doc [1], we have the following descriptions:
<img width="686" alt="Screenshot 2020-08-18 at 13 37 12" src="https://user-images.githubusercontent.com/21237558/90487390-1130bd80-e158-11ea-8288-e0e13184d065.png">

In the rabbitMQ inbound properties doc [2], we have the following descriptions:
<img width="684" alt="Screenshot 2020-08-18 at 13 39 42" src="https://user-images.githubusercontent.com/21237558/90487605-51903b80-e158-11ea-9b8f-a8cb69d534c1.png">
<img width="684" alt="Screenshot 2020-08-18 at 13 39 51" src="https://user-images.githubusercontent.com/21237558/90487612-548b2c00-e158-11ea-8619-293ea81ea2d0.png">

@sachithKay - Is it correct to use one description for both. If so, how about the following:

- rabbitmq.exchange.autodeclare
   "Whether or not to declare the exchange. If set to 'true' the Micro Integrator creates exchanges if they are not already 
    present. If set to 'false', the Micro Integrator will assume that an exchange is already available.
    However, you should set this parameter only if exchanges are not declared prior on the broker. Setting this parameter in the 
    publish URL to false improves RabbitMQ transport performance."

- rabbitmq.queue.autodeclare
  "Whether or not to declare the queue. If set to 'true' the Micro Integrator creates queues if they are not already 
    present. If set to 'false', the Micro Integrator will assume that an queue is already available.
    However, you should set this parameter only if queues are not declared prior on the broker. Setting this parameter in the 
    publish URL to false improves RabbitMQ transport performance."

@sachithKay , what do we mean by this statement?
*However, you should set this parameter only if queues are not declared prior on the broker*

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/transport-parameters/rabbitmq-transport-parameters/
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/

**Comment by sachithKay** [comment]
@nilminiwso2 
Yes, same explanation should suffice for both instances. Please find the descriptions below.

 - rabbitmq.exchange.autodeclare
"Whether or not to declare the exchange. If set to 'true' the Micro Integrator creates exchanges and If set to 'false', the Micro Integrator will assume that an exchange is already available.
However, you should set this parameter **as true** only if exchanges are not declared prior on the broker. Setting this parameter in the publish URL to false improves RabbitMQ transport performance."

- rabbitmq.queue.autodeclare
"Whether or not to declare the queue. If set to 'true' the Micro Integrator creates queues if they are not already
present. If set to 'false', the Micro Integrator will assume that an queue is already available.
However, you should set this parameter as true only if queues are not declared prior on the broker. Setting this parameter in the publish URL to false improves RabbitMQ transport performance."

However, you should set this parameter only if queues are not declared prior on the broker - means you should only set this property to true, if you haven't declared the queue or exchange beforehand in the rabbitMQ side.
If this is set to true, we will consume more time to declare them, hence the performance reduction. If set to false, it will have higher performance.

**Comment by nilminiwso2** [comment]
Added the following descriptions through [1].

- rabbitmq.exchange.autodeclare
- rabbitmq.queue.autodeclare

[1] https://github.com/wso2/docs-ei/pull/2242/files#diff-7a89eae395f17a21e73cc350248e7e20

**Comment by nilminiwso2** [comment]
Additional fix: https://github.com/wso2/docs-ei/pull/2301

**Comment by nilminiwso2** [comment]
Fixed (rabbitmq.exchange.autodeclare/rabbitmq.queue.autodeclare)

- http://0.0.0.0:8000/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/#optional-properties
- http://0.0.0.0:8000/references/synapse-properties/transport-parameters/rabbitmq-transport-parameters/

Fixed (SET_ROLLBACK_ONLY/SET_REQUEUE_ON_ROLLBACK):

- https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/property-reference/generic-Properties/#rabbitmq-properties
- https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/transport-parameters/rabbitmq-transport-parameters/#mediator-properties
- https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/#mediator-properties
