### ISSUE TITLE
Rabbitmq message store doc - Improvements.

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-ei#1746]
**Description:**
In https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/examples/message_store_processor_examples/using-rabbitmq-message-stores/
The following config works.
```
<?xml version="1.0" encoding="UTF-8"?>
<messageStore class="org.apache.synapse.message.store.impl.rabbitmq.RabbitMQStore" name="rabbit" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="store.rabbitmq.host.name">localhost</parameter>
    <parameter name="store.producer.guaranteed.delivery.enable">false</parameter>
    <parameter name="store.rabbitmq.host.port">5672</parameter>
    <parameter name="store.rabbitmq.route.key"/>
    <parameter name="store.rabbitmq.username"/>
    <parameter name="store.rabbitmq.virtual.host"/>
    <parameter name="rabbitmq.connection.ssl.enabled">false</parameter>
    <parameter name="store.rabbitmq.exchange.name"/>
    <parameter name="store.rabbitmq.queue.name">xyz</parameter>
    <parameter name="store.rabbitmq.password"/>
</messageStore>
```

Further it should link to https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/brokers/configure-with-rabbitMQ/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
[1] is already updated with the given config. Also, the link to 'configuring a RabbitMQ broker' is updated.

Please reopen if you find any other issues.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/message_store_processor_examples/using-rabbitmq-message-stores/
