### ISSUE TITLE
Management API is enabled by default and the doc needs to be changed. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1764]
**Description:**
Doc: 
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/using-the-command-line-interface/
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/

The management API is enabled by default and we do not need to explicitly enable it in the startup. Therefore the doc needs to be edited.

**Comment by nilminiwso2** [comment]
Fixed in https://github.com/wso2/docs-ei/issues/1642
