### ISSUE TITLE
Add troubleshooting unit testing framework 

### ISSUE THREAD

**Issue by prabushi** [wso2/docs-ei#1765]
**Description:**
We can use the following steps to troubleshoot the Synapse Unit testing framework
1.Select **Run** -> **Run Configurations..**
2. Select '**Run Unit Test Internal Configuration**' under '**Maven Build**'
3. Add **-X** to the end of  'Goals' (to enable maven debug for the testing framework)
4. Then, click on **Apply** and **Run**
![unit-test](https://user-images.githubusercontent.com/5234623/87390348-5183a580-c5c6-11ea-8184-5e6098ec0f7d.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed by:
- https://github.com/wso2/docs-ei/pull/2406
- https://github.com/wso2/docs-ei/pull/2409
