### ISSUE TITLE
[Micro Integrator] Issues in the File-Connector sample 

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-ei#1778]
**Description:**
In the following document [1] which contains a sample for the File-Connector, the following points should be corrected. 

1. In order to add the connector in the Integration Studio, the "File" connector should be searched in step-3 under "Configure the connector in WSO2 Integration Studio". Since this is not mentioned, it can be misleading. A screenshot with the correct connector (File) will avoid any confusions. Please refer to the following screenshot. 

![add-File](https://user-images.githubusercontent.com/5971789/87698996-d979d300-c7b1-11ea-92f3-d660d9bb2669.png)

2. Under the "Creating the Integration Logic" section, step-3 should be updated with the "filepath" parameter instead of "source" ("source" refers to an old implementation). Please refer to the following screenshot. 

![filepath](https://user-images.githubusercontent.com/5971789/87699819-0975a600-c7b3-11ea-8da5-c520e33d373a.png)

3. According to the above update, step-16 under the "Creating the Integration Logic" should also be updated with the correct synapse configurations including the "filepath" parameter instead of "source". Please refer to the following configurations. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<api context="/fileconnector" name="FileConnector" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST" url-mapping="/create">
        <inSequence>
            <log level="custom">
                <property name="test" value="xxxxxxxxxxxxxxxxxxxx"/>
                <property expression="json-eval($.source)" name="source"/>
                <property expression="json-eval($.inputContent)" name="inputContent"/>
            </log>
            <property expression="json-eval($.source)" name="source" scope="default" type="STRING"/>
            <property expression="json-eval($.inputContent)" name="inputContent" scope="default" type="STRING"/>
            <fileconnector.create>
                <filePath>{$ctx:source}</filePath>
                <inputContent>{$ctx:inputContent}</inputContent>
                <source>{$ctx:source}</source>
            </fileconnector.create>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
    <resource methods="POST" url-mapping="/read">
        <inSequence>
            <property expression="json-eval($.source)" name="source" scope="default" type="STRING"/>
            <fileconnector.isFileExist>
                <source>{$ctx:source}</source>
            </fileconnector.isFileExist>
            <property expression="json-eval($.fileExist)" name="response" scope="default" type="STRING"/>
            <log level="custom">
                <property expression="get-property('response')" name="responselog"/>
            </log>
            <switch source="get-property('response')">
                <case regex="true">
                    <fileconnector.read>
                        <source>{$ctx:source}</source>
                    </fileconnector.read>
                    <respond/>
                </case>
                <default>
                    <log>
                        <property name="notext" value="&quot;File does not exist&quot;"/>
                    </log>
                </default>
            </switch>
            <drop/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
4. The file that needs to be created under "Testing" should be "body.json" and not "data.json".

[1]. https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/connectors/file-connector/file-connector-example/#!

**Affected Product Version:** MI-7.1.0

**Comment by Shakila** [comment]
Please find the resolution for the above concerns.
1. We use common content for the general topics. Hence used the sample connector for this.
2. If you are using the latest connector please refer the latest doc [1]. Which is available under 4.x.
[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/file-connector/file-connector-example/
3. Fixed.
4. Fixed.
