### ISSUE TITLE
MI - ADMIN and OBSERVE section (SNMP Monitoring)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#179]
Complete the docs on SNMP monitoring [1].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/snmp_monitoring/

**Comment by nilminiwso2** [comment]
@isudana - Is this topic still valid for the Micro Integrator?
If it is still valid, I feel we need to add more information to this on why this feature is needed and how it can be used.

**Comment by AlisonAbrantes** [comment]
Is this task still on improvement? I opened an issue with the process described on documentation, apparently it's not working.
Can you given us, more information about this feature?

Link: https://github.com/wso2/api-manager/issues/791

**Comment by chanikag** [comment]
This is available in MI docs https://mi.docs.wso2.com/en/latest/observe-and-manage/classic-observability-metrics/snmp-monitoring/
