### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by KendallWheeler12** [wso2/docs-ei#1790]
Location : https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/file-processing/
Directions state:
"Click the '+' icon in the lower section and add the following drivers and libraries.
(https://github.com/wso2-docs/WSO2_EI/blob/master/Integration-Tutorial-Artifacts/Artifacts-fileProcessingTutorial.zip)

MySQL database driver.
CSV smooks library.
Note

These are copied to the /lib folder of the embedded Micro Integrator."

The read me files inside say different areas. For example "Copy the smooks-config.xml file in to resources/ directory."

Need guidance on where exactly to put the demo files within micro integrator to complete this exercise.

**Comment by nilminiwso2** [comment]
We've updated this section in the docs: https://github.com/wso2/docs-ei/pull/2187/files 
The correct file path is '/lib'. We don't need the readme anymore.

Thank you for reporting this!
