### ISSUE TITLE
[Integration Studio] Docker build image fails saying the system cannot find the file specified

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#1798]
**Description:**
When the **Docker has not started**, the docker image build will fail with the following error message.
In that case, please check whether Docker is running and retry.

![Screenshot (83)](https://user-images.githubusercontent.com/25482980/88134570-9d57cf80-cc02-11ea-873d-577ec191c974.png)

**Comment by nilminiwso2** [comment]
fixed by https://github.com/wso2/docs-ei/pull/2616/commits/7a83777c95d73dde425d4331a481a3125c160a0d
