### ISSUE TITLE
[Micro Integrator] CHARACTER_SET_ENCODING property alone, does not work as expected

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/docs-ei#1808]
**Description:**
As per the documentation [1] with the use of "CHARACTER_SET_ENCODING" property in the mediation, we can specify the encoding type used for the content of the files/payloads processed by the transport. 

But as per the observation when testing with the Micro Integrator-7.1.0, it requires both "messageType" and "CHARACTER_SET_ENCODING" properties to change the charset from the Content-Type header and to change the encoding type,
```
            <property name="messageType" scope="axis2" value="application/json; charset=Windows-1251"/>
            <property name="CHARACTER_SET_ENCODING" scope="axis2" type="STRING" value="Windows-1251"/>
```
It would be better if a note can be added into the documentation [1] providing the above information.

**Affected Product Version:**
MI-7.1.0

[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/mediators/property-reference/axis2-properties/#character_set_encoding

**Comment by Shakila** [comment]
Unable to re-create the same. CHARACTER_SET_ENCODING works even without the messageType. We suspect that the content type might not be defined for the in-flow of this scenario.
