### ISSUE TITLE
No doc found in EI 7 for JSON Transform Mediator

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1810]
**Description:**
$subject. 

EI 6.6. docs: 
https://docs.wso2.com/display/EI660/JSON+Transform+Mediator

This mediator is not listed here. 
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/mediators/about-mediators/

**Comment by arunans23** [comment]
Duplicated issue https://github.com/wso2/docs-ei/issues/1860. Hence closing this.
