### ISSUE TITLE
[SAP Integration] Add jars to the doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1827]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/sap-integration/

Since the following jars are hard to find, shall we commit the jars here  https://github.com/wso2-docs/WSO2_EI and refer them in the doc. 

The following jars and dll file needs to be added.

- sapidoc3.jar 
- sapjco3.jar
- sapjco3.dll

Further add the following Windows commands as well
**Section: Installing the SAP Adapter**
Step6

**Configuring WSO2 SAP Adapter**
Step3
Sending BAPIs
Receiving BAPIs

**Comment by Nirothipan** [comment]
I guess the jars are proprietary and cannot be added +@sdkottegoda please confirm

**Comment by sdkottegoda** [comment]
We cannot add the jars to the documentation since these are proprietary.

**Comment by nilminiwso2** [comment]
@sdkottegoda - shall we add the Windows command to the docs?
