### ISSUE TITLE
[File processing] Add the complete script to create database and tables. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1846]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/file-processing/
Shall we add the complete script to create the database and the tables? Further, mention the database name to be created in the beginning of the doc. 

````
delimiter $$

CREATE TABLE `info` (
  `name` varchar(45) DEFAULT '',
  `surname` varchar(45) DEFAULT NULL,
  `phone` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$
````

The following syntax does not create the entries in the table.

**Comment by Nirothipan** [comment]
The intention of this sample is to give user an idea how to insert records from file to a database. As the doc already provides script to create table, its sufficient IMO. Instructing the user, how to create a db is bit out of the scope, wdyt ?

**Comment by isuruuy429** [comment]
Closing the issue as the provided steps are enough to setup the database.
