### ISSUE TITLE
[Reusing Mediation Sequences] Add the complete XML configuration

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1848]
**Description:**
doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/using-templates/
It would be better if we can add the complete xml configuration since in Update the mediation flow section, it is asked user to repeat some steps for other hospitals as well. It would be useful if the final xml configuration is added after completing all the steps. 

Further, to this example, as the pre packaged project, we use [this project](https://github.com/wso2-docs/WSO2_EI/blob/master/Integration-Tutorial-Artifacts/Integration-Tutorial-Artifacts-EI7.1.0/sending-simple-message-tutorial.zip). 
The screenshots seems to be different in the given API.

**Comment by Nirothipan** [comment]
@SanojPunchihewa will be working on this
