### ISSUE TITLE
Doc Feedback: URL not found in https://ei.docs.wso2.com/en/7.1.0/setup/user_stores/setting_up_a_userstore

### ISSUE THREAD

**Issue by glaucioguerra** [wso2/docs-ei#1853]
Hi,

In the Location : https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/working-with-monitoring-dashboard when I try to open setting up a user store the link is not found (https://ei.docs.wso2.com/en/7.1.0/setup/user_stores/setting_up_a_userstore). I tried to the old documenation version, same behavior.

**Comment by nilminiwso2** [comment]
Fixed.
Thanks for reporting.
