### ISSUE TITLE
[Doc] Property mediator document content is not adhere to our recommendation 

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-ei#1858]
**Description:**

We advice customers to use $ctx: syntax whereever possible. But seems out property mediator doc still promotes get-property() syntx.

https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/property-Mediator/

We need to update the content?

**Comment by Nirothipan** [comment]
Refactored the above doc to give prominence about the $ctx compared to get property and updated the applicable examples https://github.com/wso2/docs-ei/pull/2648
