### ISSUE TITLE
Document on how to apply secure vault when building an Docker image of WSO2 MI

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-ei#1864]
**Description:**

There should be a guide on how to apply secure vault when you are building Docker images of WSO2 MI. If that is not needed when deployed with K8S/Docker, we need to mention it clearly as well. 

(In general, I feel all MI related docs are VM oriented still and we have not thought of the experience of a customer who will be doing deployments using images)

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by nilminiwso2** [comment]
Closing this issue now, as the feature and docs are completed for the EI 7.1.0 release. 
An additional improvement will be handled by [2].

[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/security/encrypting_plain_text/
[2] https://github.com/wso2/docs-ei/issues/2131
