### ISSUE TITLE
[File Connector][Append]Provide an example of how we can append the text to an exact position

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1869]
**Description:**
Doc: https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/file-connector/file-connector-config/

It is better if we can provide the details on how to append the text and the behavior if it, and which input that we need to provide.

**Comment by Shakila** [comment]
The Integration Studio properties view help tip tells about the property. Hence closing this ticket.

<img width="516" alt="HelpTip" src="https://user-images.githubusercontent.com/2033965/102966979-fbbd0d00-4516-11eb-9c55-ded4ca9dab87.png">
