### ISSUE TITLE
Stockquote sample getFullQuote operation is not working.

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-ei#1874]
**Description:**
Followed [1] and the getFullQuote operation is not working in the stockquote sample backend.

It gives following error,

error: {ballerina/mime}HeaderNotFound message=Http header does not exist
	at ballerina.mime.Entity:getHeader(natives.bal:341)
	   ballerina.http.Request:getHeader(http_request.bal:118)
	   wso2.stockquote_service.services__service_0:SimpleStockQuoteService(mock_soap_service.bal:31)

[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/examples/proxy_service_examples/Introduction-to-Proxy-Services/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
As we do not have any function written to handle soap action getFullQuote in [1], the above error is thrown. Also the stock quote service does not work in JDK11.
We can use the jar available in [2] as an alternative. But we need to modify our documentations accordingly.

[1] https://github.com/wso2-docs/WSO2_EI/blob/master/Resources/SOAP-Service/src/stockquote_service/mock_soap_service.bal
[2] https://github.com/wso2/msf4j/tree/master/samples/stockquote/fatjar

**Comment by Vathsan** [comment]
Closing this issue since it is fixed in https://github.com/wso2-docs/WSO2_EI/pull/74 with JDK 11 support.
