### ISSUE TITLE
Managing the Registry

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#1910]
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/creating-artifacts/registry/managing-the-Registry/

**Comment by nilminiwso2** [comment]
The former page on 'managing the Registry' is now redirected to [1] because the content is no longer applicable to MI.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/creating-registry-resources/
