### ISSUE TITLE
Update RDBMS user store docs

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-ei#1998]
**Description:**
From the PR [1] onwards, the user_store mapping logic has been changed as follows.
 ```
[user_store]
type = "read_only_ldap" 
```
possible values for user_store.types as follows.
- database
- read_only_ldap

Hence, in wso2mi-1.1.0+1574768470645 onwards, the user stores have to be configured as below.

LDAP user store:
```
[user_store]
connection_url = "ldap://localhost:10389"  
connection_name = "uid=admin,ou=system"
connection_password = "admin"  
user_search_base = "ou=Users,dc=wso2,dc=org"
type = "read_only_ldap"
```
RDBMS user store:
```
[user_store]
class = "org.wso2.micro.integrator.security.user.core.jdbc.JDBCUserStoreManager"
type = "database"
```
Therefore, the documentation [2] has to be updated accordingly.

**Affected Product Version:**
MI-1.1.0

[1] - https://github.com/wso2/micro-integrator/pull/1037
[2] - https://ei.docs.wso2.com/en/latest/micro-integrator/setup/user_stores/setting_up_ro_ldap/#configuring-an-rdbms-user-store-optional

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/docs-ei/pull/2629
