### ISSUE TITLE
Doc Feedback: Typo 'Fisrt' >> 'First'

### ISSUE THREAD

**Issue by johnpwhite** [wso2/docs-ei#2035]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/develop/debugging-mediation/

"5. Invoke the service using SOAP UI or some external client. As soon as a request comes to the proxy service **fisrt** break point will be triggered."

**Comment by nilminiwso2** [comment]
Fixed.
Thanks for reporting.
