### ISSUE TITLE
Data service security not working without adding rampart module to axis2.xml

### ISSUE THREAD

**Issue by rosensilva** [wso2/docs-ei#2037]
**Description:**
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/creating-artifacts/data-services/securing-data-services/ doc need to mention that users need to add Rampart as a module as mentioned in the following doc https://docs.wso2.com/display/EI611/Engaging+Modules

**Comment by arunans23** [comment]
Created an issue to validate the documentation in MI. https://github.com/wso2/micro-integrator/issues/2031

**Comment by nilminiwso2** [comment]
closing the doc issue as we have created an issue in the product.
