### ISSUE TITLE
Consolidate 'debugging' features of Integration Studio

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#2127]
- Debugging a class mediator (New content)
   
    Steps to debug the class mediator:
    - Start the embedded server with debug mode: 
       1. Click on the drop down arrow near the Run button and select Run Configurations.
       2. Click on Generic Server > Micro Integrator Server x.x.x
       3. Go to “Arguments” tab and add the following to the VM arguments pane.
            `-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005`
       4. Click Apply > Close to add the newly configured Micro Integrator server.
       5. Click on the drop down arrow near the Run button and Microei_Run_Profile to start the server in debug mode. 
    - Start  the remote debug client
       1. Click on the drop down arrow near the Debug button and Debug Configurations.
       2. Add a new Remote Java Application profile with relevant connection properties (e.g: host - localhost, port: 5005).
       3. Click on Apply > Debug
    - Add breakpoints in the relevant class mediator and invoke the mediation flow.

- Test and review: https://ei.docs.wso2.com/en/latest/micro-integrator/develop/debugging-mediation/

**Comment by Nirothipan** [comment]
@SanojPunchihewa is working on this

**Comment by nilminiwso2** [comment]
Few more updates in progress!
