### ISSUE TITLE
Old EI version mentioned in latest SI installation doc

### ISSUE THREAD

**Issue by niruhan** [wso2/docs-ei#2163]
**Description:**
https://ei.docs.wso2.com/en/latest/streaming-integrator/setup/installing-si-in-vm/#!

The above page still has 7.0.2 EI version. Should be changed to 7.1.0

**Comment by RukshiW** [comment]
Corrected via https://github.com/wso2/docs-ei/pull/2149.

**Comment by RukshiW** [comment]
Corrected this.
