### ISSUE TITLE
Include details regarding 'legacy-encoding' in Micro Integrator documentation

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/docs-ei#2199]
**Description:**
It would be better if details regarding the use of `legacy-encoding:` while configuring HTTP endpoint parameters are included in the Micro Integrator documentation. The details are already available in the Enterprise Integrator documentation [1].

**Affected Product Version:**
EI 7.1.0

[1] https://docs.wso2.com/display/EI650/HTTP+Endpoint#HTTPEndpoint-Parameters

**Comment by Nirothipan** [comment]
@SanojPunchihewa will be working on this
