### ISSUE TITLE
Doc Feedback: is the Rule Mediator still available in Micro Integrator?

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-ei#2219]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/rule-Mediator/

Please remove the rule mediator from the list of mediators if it is no more supported in Micro Integrator.

**Comment by samgnaniah** [comment]
Please note that we have now removed this page and updated the About this Release page. Please refer to PR for details.
