### ISSUE TITLE
Information on adding custom log appenders to MI

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/docs-ei#2260]
**Description:**
We cannot use log4j2 extensions such as custom appenders and customer layout directly with the MI. For example, custom appender [1] cannot be used with MI by adding its jars to <MI_HOME>/libs folder.

- Log4j2 in WSO2 Micro Integrator works in an OSGI environment. Therefore, in order for custom appenders to work, we need to build the module containing the appender (the custom appender class that we refer to in log4j2.properties file) as a plugin. In the custom appender [1], it is the appender-log4j2 module that contains Log4j2Appender class. 
- To build it as a plugin, we need to use the maven-bundle-plugin with maven-compiler-plugin in the pom.xml file of the relevant module, which is the appender-log4j2 module in this case. Please find the configuration[2] I have used in the pom.xml file of the module. 
- Then you should rebuild the related module with this configuration and add the plugin created in target folder to <MI_HOME>/dropins. 
- Finally, the custom appender can be configured as following.
```properties 
appender.log4j2Custom.type = Log4j2Appender
appender.log4j2Custom.name = log4j2Custom
appender.log4j2Custom.layout.type = PatternLayout
appender.log4j2Custom.layout.pattern = [%d] %5p {%c} - %m%ex%n
```

[1]. https://github.com/bluedenim/log4j-s3-search
[2]. [pom.zip](https://github.com/wso2/docs-ei/files/5217909/pom.zip)

**Suggested Labels:**Improvements

**Comment by nilminiwso2** [comment]
PR to master: https://github.com/wso2/docs-ei/pull/2681/files
