### ISSUE TITLE
Missing passthru-http.properties

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-ei#2261]
**Description:**
Some properties including the following are not included in the config catalog under the passthru-http.properties.
message.size.validation.enabled
valid.max.message.size.in.bytes

[1]. https://ei.docs.wso2.com/en/latest/micro-integrator/references/config-catalog/#http-transport

**Affected Product Version:** EI-7.1.0

**Comment by madushadhanushka** [comment]
This content should go under [transport.http] passthru transport section in config catalog
**message.size.validation.enabled**
property name: enable_message_size_validation
type: boolean
default: false
description: If this property enabled and payload exceed the size of valid payload size, then discontinue reading input stream to prevent out of memory issues.

**valid.max.message.size.in.bytes**
property name: max_message_size_bytes
type: integer
default: 2147483647
Description: The size of the payload to discontinue reading input stream if enable_message_size_validation property enabled.

**max_open_connections**
property name: max_open_connections
type: integer
default: -1
description:  This property let connection throttling to restrict the number of simultaneous open connections. This will restrict simultaneous open incoming connections to the given value. To disable throttling, delete the max_open_connections setting or set it to -1.

**force.xml.message.validation**
property name: force_xml_validation
type: boolean
default: false
description: Validate the badly formed XML message by building the whole XML document. This validation ensures that erroneous XML messages are rejected by the ESB.

**force.json.message.validation**
property name: force_json_validation
type: boolean
default: false
description: Check for invalid JSON message by parsing the input message. This validation ensures that erroneous JSON messages are rejected by the ESB.

**Comment by nilminiwso2** [comment]
This should apply to [transport.blocking.http] as well?
@madushadhanushka
