### ISSUE TITLE
Incorrect URLs to access the business rules UI in the SI tooling component

### ISSUE THREAD

**Issue by Shenavi** [wso2/docs-ei#2275]
**Description:**
Currently the documentation https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/creating-business-rules-templates/ shows two incorrect URLs to access the business rules UI.

It should be corrected as https://0.0.0.0:9743/business-rules/

**Comment by RukshiW** [comment]
Corrected the URL mentioned in [1].

[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/creating-business-rules-templates/
