### ISSUE TITLE
Suspend and resume actions are not implemented in the transaction mediator

### ISSUE THREAD

**Issue by Thilinika** [wso2/docs-ei#2300]
**Description:**
Documentation include suspend and resume actions for the Transaction mediator, but they are not implemented. Please remove these parameters from all the documents

https://github.com/wso2-support/wso2-synapse/blob/support-2.1.7-wso2v143/modules/core/src/main/java/org/apache/synapse/mediators/transaction/TransactionMediator.java#L79

**Comment by Nirothipan** [comment]
Removed from https://docs.wso2.com/display/EI660/Transaction+Mediator and Mi docs.
