### ISSUE TITLE
Doc Feedback: The example fails in Integration Studio 7.1.0

### ISSUE THREAD

**Issue by robbla** [wso2/docs-ei#2352]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/endpoint_examples/using-static-recepient-list-endpoints/

Either the samp[le is incorrect or Integration Studio is not able to handle it.

![image](https://user-images.githubusercontent.com/11582659/95552845-b9069100-0a0d-11eb-946e-e815eb7ccf1d.png)

**Comment by arunans23** [comment]
@robbla Thank you reporting the issue. It seems Integration Studio currently cannot handle this properly. Creating an issue in Integration studio repo to track this. https://github.com/wso2/integration-studio/issues/37
