### ISSUE TITLE
[Micro Integrator] Issues in the Kafka Connector sample

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/docs-ei#2363]
**Description:**
In the documentation [1] which contains a sample for the Kafka Connector, the following points should be corrected.

1. To use the Kafka connector, it requires [Apache Kafka](https://kafka.apache.org/) server to be downloaded and installed. The documentation [2] has the steps to be followed in order to set up Kafka. But documentation [1] should have a reference to documentation [2] as the initial steps follow when building the sample for Kafka connector. 

2. Documentation [2] has several improvement points including incomplete sentences. Please find specific points below,

-  In the step-1 to configure the Kafka connector, the client libraries should be copied from the <KAFKA_HOME>/lib directory to the <MI_HOME>/lib directory. In [2], this is mentioned as <PRODUCT_HOME>/repository/components/lib directory and it should be corrected.

-  In the next step, the command to start the ZooKeeper server should be executed from the <KAFKA_HOME>,
`bin/zookeeper-server-start.sh config/zookeeper.properties`

-  The next command to start the Kafka server should also be executed from the <KAFKA_HOME>,
`bin/kafka-server-start.sh config/server.properties`

3. In order to add the connector in the Integration Studio [1], the "Kafka" connector should be searched in the step under "Configure the connector in WSO2 Integration Studio". Since this is not mentioned, it can be misleading. A screenshot with the correct connector (Kafka) will avoid any confusion. Please refer to the following screenshot.
![kafka_connector](https://user-images.githubusercontent.com/38277473/95831028-25f39100-0d56-11eb-937f-37e86d12e74a.png)

4. In the sub-step 7 under "Configure the connector in WSO2 Integration Studio" the XML configuration of the API should include the mandatory parameter ``<name>Unique name to identify the connection by.</name>`` in the ``<kafkaTransport.init>`` operation. Please refer to the PR [3].
The synapse configuration should be updated as follows,
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/publishMessages" name="KafkaTransport" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <kafkaTransport.init>
               <name>Sample_Kafka</name>
               <bootstrapServers>localhost:9092</bootstrapServers>
               <keySerializerClass>org.apache.kafka.common.serialization.StringSerializer</keySerializerClass>
               <valueSerializerClass>org.apache.kafka.common.serialization.StringSerializer</valueSerializerClass>
               <maxPoolSize>100</maxPoolSize>
            </kafkaTransport.init>
            <kafkaTransport.publishMessages>
                <topic>test</topic>
            </kafkaTransport.publishMessages>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
5. The above detail regarding the mandatory parameter ``<name>Unique name to identify the connection by.</name>`` in the ``<kafkaTransport.init>`` operation should also be included in the documentation [4] as well.

6. The documentation [1] should include the details on "Exporting Integration Logic as a CApp".

- This section should include details on "Creating Connector Exporter Project" in order to bundle the connector into the CApp. 

- Then it should also include details on "Creating a Composite Application Project" to export the Integration Project including the Connector Exporter Project as a CApp.

7. The "Get the project" section includes the File Connector sample in the documentation [1]. That should be corrected to include the Kafka Connector sample.

8. The "Testing" section in the documentation [1] contains incomplete information on how to test the created sample. These details should also be corrected.

- The "Sample Request" should be as follows,
```
curl -X POST -d '{"name":"sample"}' "http://localhost:8290/publishMessages" -H "Content-Type:application/json" -v
```

**Affected Product Version:**
MI-7.1.0, MI-7.2.0

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/kafka-connector/kafka-connector-producer-example/
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/kafka-connector/setting-up-kafka/
[3] https://github.com/wso2-extensions/esb-connector-kafka/pull/50
[4] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/kafka-connector/kafka-connector-config/

**Comment by samgnaniah** [comment]
All of these are fixed in the linked PR excluding point 3. For this our strategy is to use common docs that are single sourced and used in all connector docs. Hence these cannot be customized specifically for Kafka.
