### ISSUE TITLE
Update the failover endpoint docs 

### ISSUE THREAD

**Issue by 1akshitha** [wso2/docs-ei#2439]
**Description:**
We have added two properties to the synapse.properties to limit the number of retries for an endpoint to prevent unlimited retry attempts. The two configs are as follows.

1. maximum.failover.retries [ Default unlimited]
2. suspend.duration.on.maximum.failover [Default 30000ms]

**Affected Product Version:**
APIM team is creating the wum for apim 2.6.0 and soon will create another for the respective EI version. (EI 6.4.0)

**Related Issues:**
https://github.com/wso2/product-apim/issues/9405

**Comment by lasanthaS** [comment]
This information has been added to the EI 6.4.0 documentation at [1]. For the Micro-Integrator these two parameters need to be added via the template. 

[1] https://docs.wso2.com/display/EI640/Configuring+Failover+Endpoints

**Comment by madushadhanushka** [comment]
MI template update https://github.com/wso2/micro-integrator/pull/2029
