### ISSUE TITLE
File content get encoded when using multipart/form-data

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/docs-ei#2461]
When we send a multipart/form-data request and the message gets build org.apache.axis2.builder.MultipartFormDataBuilder class gets invoked and based on the default implementation of the org.apache.axis2.builder.MultipartFormDataBuilder class file content (that we send in the multipart/form-data request) gets encoded when the request is going to the backend.

This has been reported in the following git issues.
https://github.com/wso2/product-ei/issues/1525
https://github.com/wso2/product-apim/issues/9375

In order to take the effect of the code improvements provided as the fixes for the above issues, the user has to add the following property as a mediation sequence. Users can prevent the encoding of the file content by setting the following property.
`<property name="DECODE_MULTIPART_DATA" value="true" scope="axis2" action="set" type="BOOLEAN"/>
`

**Comment by nilminiwso2** [comment]
@ErandiPraboda If this is a WUM update can you provide the applicable product versions and the date on which the WUM updates are available?
