### ISSUE TITLE
HashiCorp secure-vault Integration with EI 6.6.0 and MI 1.2.0

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/docs-ei#2467]
From the **EI 6.6.0** and **MI 1.2.0** (latest WUM packages), we have enabled the $subject to our server runtimes. By following the below steps, we could integrate the external HashiCorp vault with EI server. Here we can use either [static-token](https://learn.hashicorp.com/tutorials/vault/tokens?in=vault/auth-methods) (RootToken) or [AppRole-pull method](https://learn.hashicorp.com/tutorials/vault/approle) (roleId and secretId) approach to authenticating with the HashiCorp server. 

1. Add HashiCorp vault server configurations.

- In **EI 6.6.0**,  configure the **external-vaults.xml** file which located in **<EI_HOME>/conf/security** directory.
```xml
<secureVaults>
    <!-- Uncomment this and configure as appropriate for HashiCorp secure vault support -->
    <vault name="hashicorp">
        <!-- Server address to be used in the http communication -->
        <parameter name="address">http://127.0.0.1:8200</parameter>
        <!-- Server address to be used in the https communication -->
        <parameter name="address">https://127.0.0.1:8200</parameter>
        <!-- Root token parameter for authenticate with the HashiCorp vault server-->
        <parameter name="rootToken">root_token</parameter>
        <!-- roleId and secretId parameter used to AppRole Pull authenticatation with the HashiCorp vault server -->
        <parameter name="roleId">ROLE_ID</parameter>
        <parameter name="secretId">SECRET_ID</parameter>
        <!-- All resources fetched from the HashiCorp vault would be cached for this number of milliseconds -->
        <parameter name="cachableDuration">15000</parameter> 
        <!-- Version of the HashiCorp secret engine -->
        <parameter name="engineVersion">2</parameter>
        <!-- HashiCorp namespace across the runtime -->
        <parameter name="namespace">namespace</parameter> 
        <!-- SSL configuration. By defaults truststore and keystore files are pointed to the default WSO2 JKS files. 
             Can define paths as both absolute or relative to the ${carbon.home} -->
        <parameter name="trustStoreFile">${carbon.home}/repository/resources/security/client-truststore.jks</parameter> 
        <parameter name="keyStoreFile">${carbon.home}/repository/resources/security/wso2carbon.jks</parameter>
        <parameter name="keyStorePassword">key_store_password</parameter>
    </vault> 
</secureVaults>
```

- In **MI 1.2.0**,  configure the **deployment.toml** file which located in **<EI_HOME>/conf** directory.
```toml
[[external_vault]]
name = "hashicorp"
address = "http://127.0.0.1:8200"
rootToken = "ROOT_TOKEN"
roleId = "ROLE_ID"
secretId = "SECRET_ID"
cachableDuration = 15000
engineVersion = 2
namespace = "NAMESPACE"
trustStoreFile = "${carbon.home}/repository/resources/security/client-truststore.jks"
keyStoreFile = "${carbon.home}/repository/resources/security/wso2carbon.jks"
keyStorePassword = "KEY_STORE_PASSWORD"
```
2. Copy the [vault-java-driver](https://github.com/BetterCloud/vault-java-driver) to the <EI_HOME>/lib directory (tested with 5.1.0 version).
3. Use the following xPath function inside your Synapse mediation.
```xml
<property name="HashiCorpSecret" expression="hashicorp:vault-lookup('path-name', 'field-name') />
```
**Other Supports:**
- HTTP and HTTPS support
- Namespace support (available only in HashiCorp vault enterprise edition)
   - Can add a global namespace value in deployment.toml or external-vault.xml file
   - Can use namespace value per request in Synapse configuration
   ```xml
    <property name="HashiCorpSecret" expression="hashicorp:vault-lookup('namespace', 'path-name', 'field-name') />
   ```
- Dynamic secretId support

In the AppRole-pull authentication approach, there can be a situation like limiting SecretID usages (with parameter `secret_id_num_uses`). That means after the number of SecretID usage is reached, the SecretID expires, and you would need to generate a new one and inject that new SecretID to the running server (without server downtime). 

To achieve this requirement from the EI side, we have implemented an admin service to override the current SecretID with the new one.

**Service URL:** https://HOST:9443/services/MediationSecurityAdminService?wsdl
**Operation**: setSecretIdForHashiCorpVault
**Payload**:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.synapse/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:setSecretIdForHashiCorpVault>
         <xsd:secretId>new_secret_id</xsd:secretId>
      </xsd:setSecretIdForHashiCorpVault>
   </soapenv:Body>
</soapenv:Envelope>
```

To achieve this requirement from the MI side, we have implemented a management API to override the current SecretID with the new one.

**Service URL:** https://HOST:9164/management/external-vaults/hashicorp
**Payload**:
```json
{
  "secretId" : "new_secret_id" 
}
```
Above both ways do not persist the new **secretId** in the next server startup (affect only for the current runtime). To persist the value, we have to configure the new **secretId** in relevant configuration file respective to the EI server. 

**Refer:**
[Getting Started with HashiCorp](https://learn.hashicorp.com/tutorials/vault/getting-started-intro?in=vault/getting-started)
[Vault Enterprise Namespaces](https://www.vaultproject.io/docs/enterprise/namespaces)

**Comment by nilminiwso2** [comment]
Fixed:
- 7.1.0: https://github.com/wso2/docs-ei/pull/2659
- 6.6.0 documentation: https://docs.wso2.com/display/EI660/Using+HashiCorp+Secrets
