### ISSUE TITLE
No documentation available on adding a remote server into the Integration Studio

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/docs-ei#2479]
**Description:**
I could not find any documentation on adding a remote server into the Integration Studio (IS). I am using IS 7.2.0-Beta. 

Specifically, I am trying to add an ESB 5.0.0 server into the IS and deploy artifacts from the IS into the ESB.

I found 'Deploy on a Remote Micro Integrator' link in [intro-integration-development doc](
https://ei.docs.wso2.com/en/latest/micro-integrator/develop/intro-integration-development/) and this takes to [using-remote-micro-integrator page](https://ei.docs.wso2.com/en/latest/micro-integrator/develop/using-remote-micro-integrator/) but it does not have any info related to the Integration Studio.

I found below link (thanks to @Nirothipan )
https://docs.wso2.com/display/EI660/Working+with+WSO2+Integration+Studio#WorkingwithWSO2IntegrationStudio-UsingtheESBprofile and it had the information I needed. 

I think that information needs to come in the latest docs as well.

**Comment by Nirothipan** [comment]
@SanojPunchihewa is working on this.
