### ISSUE TITLE
Logs are being over written when the configured file size of 10mb reached and only 2 files getting created

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/docs-ei#2519]
**Description:**
As per the default configuration, in [1], If the log file size is more than 10mb, there is one file being created and it is always being over written with a new file when the new file reaches 10mb. 

So, Please update the documentation in [2] to have the log pattern as in [3]

appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}-%i.log

[1] https://docs.wso2.com/display/EI660/Logs+in+WSO2+EI+6.6.0
[2] https://docs.wso2.com/display/EI660/Managing+Log+Growth
[3] https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/managing-log-growth/

appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}.log
appender.CARBON_LOGFILE.layout.type = PatternLayout
appender.CARBON_LOGFILE.layout.pattern = [%d] %5p {%c} - %m%ex%n
appender.CARBON_LOGFILE.policies.type = Policies
appender.CARBON_LOGFILE.policies.time.type = TimeBasedTriggeringPolicy
appender.CARBON_LOGFILE.policies.time.interval = 1
appender.CARBON_LOGFILE.policies.time.modulate = true
appender.CARBON_LOGFILE.policies.size.type = SizeBasedTriggeringPolicy
appender.CARBON_LOGFILE.policies.size.size=10MB
appender.CARBON_LOGFILE.strategy.type = DefaultRolloverStrategy
appender.CARBON_LOGFILE.strategy.max = 20

**Suggested Labels:**
EI docs

**Suggested Assignees:**
EI Documentation Team

**Affected Product Version:**
6.4.0/ 6.5.0 / 6.6.0 , Please check all docs

**Related Issues:**
https://github.com/wso2/docs-apim/issues/1061

**Comment by chanikag** [comment]
https://mi.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/managing-log-growth/ this is added in MI docs
