### ISSUE TITLE
Doc Feedback:[Task resolver] Please elaborate the usage of different options

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-ei#2543]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/setup/deployment/deploying_wso2_ei/

Please elaborate the usage of different options listed under "Task resolver".
Please give sample usecases/requirements for each of them, so the user can decide what to use based on their requirement.

Also explain, when to use the "Advanced Parameters" and their impact.

**Comment by Nirothipan** [comment]
Added more info about the task resolver https://github.com/wso2/docs-ei/pull/2557. As its not recommended to modify the advance parameters and as the descriptions are already provided about them,  doesn't it suffice ?.
