### ISSUE TITLE
Doc Feedback: [SI-1.1.0] "Configuring Database and File System State Persistence" documents improvements

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/docs-ei#2682]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/configuring-Database-and-File-System-State-Persistence/

The following class names should be updated with the correct class names as below.
old : org.wso2.carbon.stream.processor.core.persistence.DBPersistenceStore
new : org.wso2.carbon.streaming.integrator.core.persistence.DBPersistenceStore

old : org.wso2.carbon.stream.processor.core.persistence.FileSystemPersistenceStore
new : org.wso2.carbon.streaming.integrator.core.persistence.FileSystemPersistenceStore

**Comment by RukshiW** [comment]
Corrected as specified.
