### ISSUE TITLE
Request minor improvement to QSG guide

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-ei#2685]
**Description:**
The json payload should be listed under pine valley hospital service endpoint which accepts a json payload. As shown in the attached image, in the QSG intro section at [1] this json payload is listed under grand oak hospital service endpoint. 
 
![mi-doc-issue](https://user-images.githubusercontent.com/28379317/104120478-39b29180-535d-11eb-9bea-031a5a66c50a.png)

This is documented correctly at [2] as shown below.
 
![correct-payload](https://user-images.githubusercontent.com/28379317/104120501-65357c00-535d-11eb-84b4-e8c9110b3099.png)

[1]. https://ei.docs.wso2.com/en/7.2.0/micro-integrator/overview/quick-start-guide/
[2]. https://ei.docs.wso2.com/en/7.2.0/micro-integrator/develop/integration-development-kickstart/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
We are revamping the quick start guide with https://github.com/wso2/docs-mi/issues/791. Hence resolving this.
