### ISSUE TITLE
Observability Cloud Native: Jaeger Configuration code snippet wrong

### ISSUE THREAD

**Issue by fjunior87** [wso2/docs-ei#2703]
**Description:**
In the doc[1], in the section "Configuring the Micro Integator to publish tracing information" we have the following code snippet:

```
[opentracing]
enable = true
logs = true
manager_host = Manager_hostname
agent_host = Agent_hostname
```

But using that snippet it is not getting the correct information for the manager and agent host. Checking the key-mappings.json, the correct keys are:

```
[opentracing]
enable = true
logs = true
jaeger.sampler.manager_host = "wso2-observability-agent"
jaeger.sender.agent_host = "wso2-observability-agent"
```

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/observability/setting-up-cloud-native-observability-in-kubernetes/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Micro-Integrator 1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Leunam14** [comment]
That works for me! Thanks a ton!

**Comment by chanikag** [comment]
Using opentelemetry option in MI docs https://mi.docs.wso2.com/en/latest/observe-and-manage/setting-up-cloud-native-observability-in-kubernetes/#configuring-the-micro-integrator-to-publish-tracing-information
