### ISSUE TITLE
Doc Feedback: CustomHeader typo

### ISSUE THREAD

**Issue by iamzili** [wso2/docs-ei#2788]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/routing_examples/routing_based_on_headers/

Hi!

There is an issue with the first requests `CustomHeader`. It should be `text/xml`, because `Message Body` is a xml.
Second option is that `Message Body` content needs to be changed to json.

Thanks

**Comment by chanikag** [comment]
Based on the CustomHeader value the response is generated. In the first case the CustomHeader is application/json and you get a JSON response. Similar behaviour is there in the second case.
