### ISSUE TITLE
Doc Feedback: The example naming and finish the window decision

### ISSUE THREAD

**Issue by dendihandian** [wso2/docs-ei#2798]
Location : https://ei.docs.wso2.com/en/7.2.0/micro-integrator/references/connectors/kafka-connector/kafka-connector-producer-example/

As always, I'm having a hard time reading the WSO2 documention.  Here I want to follow how to use kafka with EI. Here some feedback:

- Please provide the Integration Project name example by looking as the context of the Kafka connector example.
- That `Sample Connector` in WSO2 Connector Store evidence really confuse the reader, why don't you instruct us to type `Kafka` instead?
- Everytime the post mention about opening window form, it's not clear whether we need to click `Next` or `Finish` afterward.

**Comment by chanikag** [comment]
We have refactored the Kafka connector doc as in [1] with content related to VS code extension for MI. These concerns are resolved there. Hence resolving this issue.

[1] https://mi.docs.wso2.com/en/latest/reference/connectors/kafka-connector/kafka-connector-producer-example/
