### ISSUE TITLE
Doc Feedback: Kafka Inbound Endpoint Example Mislead Instruction

### ISSUE THREAD

**Issue by dendihandian** [wso2/docs-ei#2801]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/kafka-connector/kafka-inbound-endpoint-example/

1. This image is misleading to follow:
![mislead-image](https://ei.docs.wso2.com/en/latest/micro-integrator/assets/img/connectors/db-event-inbound-ep.png)

Please provide the exact in context example.

2. The Instruction to make `kafka_process_seq` and `fault` sequence isn't there. I believe these sequences must be present before we made the inbound endpoint.

**Comment by chanikag** [comment]
All the steps are given in https://mi.docs.wso2.com/en/latest/reference/connectors/kafka-connector/kafka-inbound-endpoint-example/
