### ISSUE TITLE
Doc Feedback: text of first warning in the page is truncated

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-ei#2803]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/setup/message_builders_formatters/message-relay/

**Comment by chanikag** [comment]
Moved to MI docs repo https://github.com/wso2/docs-mi/issues/904

**Comment by DinithiDiaz** [comment]
Updated the following pages:

- https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/message_builders_formatters/message-relay/
- https://ei.docs.wso2.com/en/7.0.0/micro-integrator/setup/message_builders_formatters/message-relay/
