### ISSUE TITLE
using activemq instead of EI broker in tutorial 

### ISSUE THREAD

**Issue by GeertsP** [wso2/docs-ei#2808]
**Description:**
Hi , I have followed up on all the steps enlisted in the following tutorial 
https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/

This uses Message Broker profile of WSO2 EI 6.6.0 as the (JMS)? message store.  However running this and ws02mi-4.0.0 simultaneously is a nightmare.  I am trying to convert this to using activeMQ 5.16.0 instead. 
However not very successful until now.  
Assuming it is possible to use the same constructs (a store mediator for storing messages and a message processor for picking up and starting a sequence for processing ) can someone enlighten me on how to do this please? 
So far I can run the project but as soon as it hits the message store is gives an error "[2021-06-17 14:07:03,102] ERROR {MessageStoreMediator} - {api:HealthcareAPI} Message Store does not exist"

I will enclose the CAR file of the project and the toml file of my microintegrator.
Additionally I have copied some jar files from activeMQ into the MIHome\lib directory. 
Alternative could be any example project detailing the needed constructs/definitions getting this to work with ActiveMQ but sofar I haven't been able to locate one.   

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2mi 4.0.0 Integration studio 8.00
**OS, DB, other environment details and versions:**    
win10 
[SampleServicesCompositeApplication_1.0.0.zip](https://github.com/wso2/docs-ei/files/6670212/SampleServicesCompositeApplication_1.0.0.zip)
[deployment.toml.txt](https://github.com/wso2/docs-ei/files/6670239/deployment.toml.txt)

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
These concerns are fixed in https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/storing-and-forwarding-messages/
