### ISSUE TITLE
endpoint_examples/inbound-endpoint-secured-websocket/ problem 

### ISSUE THREAD

**Issue by GeertsP** [wso2/docs-ei#2809]
**Description:**
The supplied jar files for starting websocket server and client to test things don't work 
When you supply the indicated java -cp   command for both client and server side you get a 
Error: Could not find or load main class io.netty.example.http.websocketx.server.WebSocketServer (for the server side) 
Must be an java idiosyncrasy somehow because the class indicated is definitely in the supplied jar file.   

https://ei.docs.wso2.com/en/7.2.0/micro-integrator/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-secured-websocket/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
All the steps are updated in https://mi.docs.wso2.com/en/latest/learn/examples/inbound-endpoint-examples/inbound-endpoint-secured-websocket/. Please create an issue in https://github.com/wso2/micro-integrator or https://github.com/wso2/docs-mi if you still see errors.
