### ISSUE TITLE
Path error in primary keystore section

### ISSUE THREAD

**Issue by BechtelCanDoIt** [wso2/docs-ei#2817]
**Description:**
In the configuring the primary keystore section:
This path is missing repository: <Location>${carbon.home}/resources/security/wso2carbon.jks</Location>
Should be: <Location>${carbon.home}/**repository**/resources/security/wso2carbon.jks</Location>

**Suggested Labels:**
ei-6.6.0

**Suggested Assignees:**

**Affected Product Version:**
ei-6.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Related Issues:**

**Comment by chanikag** [comment]
Fixed in MI docs https://mi.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-keystores/
