### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by jpdehaas** [wso2/docs-ei#2871]
Location : https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/examples/jms_examples/rabbitmq-examples/

Outsequence is outside target?
<outSequence>
   <drop/>
 </outSequence>

**Comment by chanikag** [comment]
OutSequence is removed in MI docs https://mi.docs.wso2.com/en/latest/learn/examples/rabbitmq-examples/point-to-point-rabbitmq/
