### ISSUE TITLE
Doc Feedback: Please add diagrams to explain usecase

### ISSUE THREAD

**Issue by milindaperera** [wso2/docs-ei#2894]
Location : https://ei.docs.wso2.com/en/7.2.0/micro-integrator/use-cases/tutorials/file-processing/

Please add diagrams to explain usecase, people don't have all day to read text.
To improve UX and convey idea/message quickly, diagrams are must

**Comment by chanikag** [comment]
https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/file-processing/
