### ISSUE TITLE
Issue with the topic - Configuring access logs for the PassThrough and NIO transports (Service/API invocation)

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-ei#2907]
**Description:**
In EI 6.6.0, there is no log4j.properties file but instead there is log4j2.properties file. Therefore, instructions in "Configuring access logs for the PassThrough and NIO transports (Service/API invocation)" topic need to be changed according to the log4j2.properties configurations. 

**Affected Product Version:**
EI 6.6.0

**Comment by chanikag** [comment]
This is fixed in MI docs https://mi.docs.wso2.com/en/latest/observe-and-manage/classic-observability-logs/configuring-log4j2-properties/#configuring-http-access-logs
