### ISSUE TITLE
Broken Images for Sample Queries documentation

### ISSUE THREAD

**Issue by BechtelCanDoIt** [wso2/docs-ei#2909]
**Description:**

https://docs.wso2.com/display/EI660/Sample+Queries#SampleQueries-Sample10:DefiningNamedparameters
Images for Sample 10 and 11 are missing. (Checked with both Safari and Chrome)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Open URL and scroll down to sample 10.
https://docs.wso2.com/display/EI660/Sample+Queries#SampleQueries-Sample10:DefiningNamedparameters

**Related Issues:**

**Comment by chanikag** [comment]
https://mi.docs.wso2.com/en/latest/reference/synapse-properties/data-services/sample-queries/
