### ISSUE TITLE
Broken links in Micro Integrator documentation

### ISSUE THREAD

**Issue by iloshinik** [wso2/docs-ei#2924]
**Description:**
On https://wso2.com/integration/micro-integrator/ the below two links are not working.

> **PREVIOUS RELEASES**
> [ENTERPRISE INTEGRATOR 6.X.X SERIES >](https://wso2.com/enterprise-integrator/6.6.0)
> 
> [ENTERPRISE INTEGRATOR 7.X.X SERIES >](https://wso2.com/integration//)

**Suggested Labels:**
Micro Integrator

**Comment by chanikag** [comment]
Now EI download packs are removed from the site.
