### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by zxhTom** [wso2/docs-ei#2955]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-secured-websocket/

dispatchSeq 、outDispatchSeq 、  endpoints 

Why doesn't the websocket protocol exist after publishing after I created three profiles following the tutorial

**Comment by chanikag** [comment]
We have tested MI docs https://mi.docs.wso2.com/en/latest/learn/examples/inbound-endpoint-examples/inbound-endpoint-secured-websocket/ and it is working. Hence closing this issue. Please open an issue in https://github.com/wso2/micro-integrator (runtime issues) or in https://github.com/wso2/docs-mi (doc issues) if you come across any issues.

**Comment by zxhTom** [comment]
邮件已收到！谢谢配合。
