### ISSUE TITLE
Doc Feedback: endpiont --> endpoint

### ISSUE THREAD

**Issue by alienfs** [wso2/docs-ei#2978]
Location : https://ei.docs.wso2.com/en/7.0.0/micro-integrator/references/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/

"Optional Properties"
The following optional properties can be configured when [creating an RabbitMQ inbound endpiont]

**endpiont** --> endpoint

**Comment by chanikag** [comment]
This is fixed in MI docs 
https://mi.docs.wso2.com/en/latest/reference/synapse-properties/inbound-endpoints/event-based-inbound-endpoints/rabbitmq-inbound-endpoint-properties/
