### ISSUE TITLE
Doc Feedback: Link to "content-aware" gives 404

### ISSUE THREAD

**Issue by alienfs** [wso2/docs-ei#2980]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/enrich-Mediator/

The link to "content-aware" is giving a 404:
https://ei.docs.wso2.com/en/latest/micro-integrator/concepts/message-processing-units/#classification-of-mediators

**Comment by chanikag** [comment]
This is fixed in MI docs, hence resolving.
