### ISSUE TITLE
A Typo is found in the documentation

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [wso2/docs-ei#3005]
## Description
> A brief description of the bug.
![image](https://github.com/user-attachments/assets/83d05717-82c5-4af8-90df-6eab72002559)
https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/property-reference/accessing-properties-with-xpath/#get-property-function

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by chanikag** [comment]
This is fixed in MI docs https://mi.docs.wso2.com/en/latest/reference/synapse-properties/expressions/#get-property-function
