### ISSUE TITLE
MI - Configuration Catalog - Maintenance and UX

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#311]
- Document the process of maintaining and updating the config catalog using the new JSON-based updateTool.
- Investigate the latest UX changes that were discussed for the product (The TOC, Code examples in tab)

**Comment by nilminiwso2** [comment]
The latest UX changes have been applied locally, and the new configs are built using the new JSON-based tool [1]. However, these are not committed to the EI doc repo yet. Awaiting a UX allocation to merge these changes.

Placing this on hold until the latest UX changes are applied.

[1] https://wso2docs-configurationcatalog-3.netlify.com/references/config-catalog/

**Comment by chanikag** [comment]
https://mi.docs.wso2.com/en/latest/reference/config-catalog-mi/ is updated now, hence resolving,
