### ISSUE TITLE
Improve script mediator docs

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#354]
We should improve our documentation around the available APIs in the script mediator with proper examples.

Related issue for EI650 [2]
Related mail thread: "WSO2 Enterprise Integrator: Script mediator"

[1] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/references/mediators/script-Mediator.md
[2] https://github.com/wso2/product-ei/issues/4380

**Comment by chanikag** [comment]
We have introduced GraalVM as the default JS engine for the js language. The MI doc is changed according to that. https://mi.docs.wso2.com/en/latest/reference/mediators/script-mediator/#examples 
Hence this improvement is invalid now.
