### ISSUE TITLE
MI - DEVELOPER section (Developing Integration)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#360]
Complete the documentation on 'Developing Integration' [1].

**Note**: Changed the initial topic list. [1] is now replaced with [2].

**For reviewers**: Please see the preview on netlify[3] as the images don't shown in github md files.

[1] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/develop/designing-integration.md
[2] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/develop/intro-integration-development.md
[3] https://wso2docs-configurationcatalog-3.netlify.com/develop/intro-integration-development/

**Comment by nilminiwso2** [comment]
Done. Need review.

**Comment by nilminiwso2** [comment]
@nandika / @isudana  - for your review.

**Comment by kasun04** [comment]
- Step 1: Can we clearly mentioned that Docker and Curl are optional. 
- Step 3: In a VM we can run the MI too (not just running the embedded one), include K8s as another option. 
- Step 4/5: Include unit testing (a reference)as part of the development process. 

Also, add Kubernetes references to the developer guide. @sajithaliyanage @nilminiwso2

**Comment by nilminiwso2** [comment]
PRs improving the 'Develop ' landing page:

- https://github.com/wso2/docs-ei/pull/2404
- https://github.com/wso2/docs-ei/pull/2405

**Comment by nilminiwso2** [comment]
Fixed.
