### ISSUE TITLE
MI - Enterprise Integration Patterns (Convert MD files)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#468]
The EIP pattern documentation is currently a separate confluence doc [1]. This content needs to be converted to MD files and moved to github.

[1] https://docs.wso2.com/display/EIP/Enterprise+Integration+Patterns+with+WSO2+Enterprise+Integrator

**Comment by chanikag** [comment]
This is moved to mi docs space. https://mi.docs.wso2.com/en/latest/learn/enterprise-integration-patterns/eip-overview/
