### ISSUE TITLE
Need to add correct images in docs

### ISSUE THREAD

**Issue by dnwick** [wso2/docs-ei#505]
**Description:**
Images in following link https://ei.docs.wso2.com/en/next/streaming-integrator/develop/working-with-the-Design-View/ and other sections are not taken from SI tooling

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
These screenshots are now replaced with the ones taken by Streaming Integrator Tooling.
