### ISSUE TITLE
Register Ballerina language for highlighting

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#512]
Need to highlight code and syntax for Ballerina. This code can be found here:

The code for this can be found here: https://github.com/ballerina-platform/ballerina-www/blob/master/website/main-pages/ballerina.io-website-theme/js/ballerina-common.js#L79-L156

**Comment by samgnaniah** [comment]
Currently code block displays as a single line when we use Ballerina syntax highlighting.

<img width="707" alt="Screen Shot 2019-09-28 at 3 01 58 PM" src="https://user-images.githubusercontent.com/19791901/65814559-021fe480-e201-11e9-90b9-6458e325b08b.png">

**Comment by nilminiwso2** [comment]
Resolved.
