### ISSUE TITLE
Add WIP tag to header

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#544]
Add a WIP label to the header of the docs until the EI 7.0.0 product release goes out.

Add the following to the theme.css file in docs-ei/en/<integrator>/docs/assets/css folder.

.beta-badge {
    display: inline-block;
    background: #ffd600;
    font-size: 14px;
    padding: 5px;
    line-height: 1;
}

Add the following next to the {{ config.site_name | replace('WSO2', '') }} snippette under <span class="md-header-nav__topic"> of the header.html file in the docs-is/en/theme/material/partials folder.

<span class="beta-badge">WIP</span>

Example:
<div class="md-flex__cell md-flex__cell--stretch">
        <div class="md-flex__ellipsis md-header-nav__title" data-md-component="title">
          {% if config.site_name == page.title %}
            {{ config.site_name }}
          {% else %}
            <span class="md-header-nav__topic">
              {{ config.site_name | replace('WSO2', '') }} <span class="beta-badge">WIP</span>
            </span>
            <span class="md-header-nav__topic">
              {{ page.title }}
            </span>
          {% endif %}
        </div>

This is the code used for other products but we have to check if this works for EI due to customized header.

**Comment by nilminiwso2** [comment]
Not required.
