### ISSUE TITLE
Add robot.txt file to enable No Follow links

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#568]
Add this to the web root.
[robots.txt](https://github.com/wso2/docs-ei/files/3621078/robots.txt)

**Comment by dakshika** [comment]
why we are disallowing all bots?

**Comment by samgnaniah** [comment]
The concern is that page titles may change before the release and cause incorrect ranking. This will be removed prior to the official release of course.

**Comment by samgnaniah** [comment]
Will close this as we are close to the release and fixing this will not have a major impact on the docs in my view.

@nilminiwso2 @RukshiW @dakshika  please note.
