### ISSUE TITLE
Current build script builds the wrong repo

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#589]
Currently the 7.0.0 branch has all the documentation for this release. However, the build script has changed last week and it now only builds master instead of the branch to ei.docs.wso2.com/en/latest.

This is the expected solution:

master branch -> ei.docs.wso2.com/en/next
7.0.0 branch -> ei.docs.wso2.com/en/latest

**Comment by dakshika** [comment]
this was partially fixed

**Comment by samgnaniah** [comment]
Fixed now.
