### ISSUE TITLE
Identify initial list of samples

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#59]
Identify initial list of samples.

**Comment by samgnaniah** [comment]
Initial competitor analysis done (note access is restricted to internal viewers):

https://docs.google.com/spreadsheets/d/1-DtHw8IyHwV60t4zbFSAZcXa2XkOSDW6FjgF9_i1PdI/edit?usp=sharing

**Comment by nilminiwso2** [comment]
Done: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/integration-use-cases/
