### ISSUE TITLE
Identify initial list of guides

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#60]
This involves competitor analysis and presenting the findings to the team so that they can make an informed decision and come up with a list.

**Comment by nilminiwso2** [comment]
The same tutorials that were in EI650 have been added [1].

**Remaining work**
- Testing with the new product pack.
- Diagrams
- New File processing tutorial. @nandika  - Will we need such a tutorial?

[1] https://github.com/wso2/docs-ei/tree/master/en/micro-integrator/docs/concepts

**Comment by nilminiwso2** [comment]
done.
