### ISSUE TITLE
Include a high level component diagram in  'Key Concepts' page

### ISSUE THREAD

**Issue by kasun04** [wso2/docs-ei#601]
- The Key concept is full of text and hardly gives the new user a good understanding of the product quickly. 
- Shall we include a single diagram to explain the core concepts of the runtime (message entry points, message processing, and exit points)?

**Comment by nilminiwso2** [comment]
Diagram added: https://ei.docs.wso2.com/en/latest/micro-integrator/overview/key-concepts/
Thanks!
