### ISSUE TITLE
Micro Integrator - Observability section structure

### ISSUE THREAD

**Issue by kasun04** [wso2/docs-ei#603]
Please restructure observability sections as follows:

- Logging
- Metrics: Prometheus, ELK, JMX, SNMP goes here
- Tracing: Jaeger goes here.

**Comment by nilminiwso2** [comment]
Done: https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/

Will apply Jaeger when implementation is done.

Thanks!
