### ISSUE TITLE
MI - Revisit 'Quick Tour - WSO2 Integration Studio'

### ISSUE THREAD

**Issue by kasun04** [wso2/docs-ei#607]
Please refer to "/Quick Tour - WSO2 Integration Studio" of MI. There are multiple issues:

- There is no reference or screenshot of the graphical editor. 
- Screenshot under the workbench is blurred and hard to read. Is that required at all? 
- The main purpose of using the integration studio is that designing mediation flows and running/debugging them. Why it is not explained simply in the quick tour along with key components of the studio.

**Comment by dakshika** [comment]
will check and update

**Comment by nilminiwso2** [comment]
Improved this content for the master branch [1]. The updates include new features to WSO2 Integration Studio.
Will merge to 7.0.0 branch after the new tooling release is finalized.

[1] https://github.com/wso2/docs-ei/pull/1254/files
