### ISSUE TITLE
Endpoint Template does not work with Integration Studio

### ISSUE THREAD

**Issue by Ibaqu** [wso2/docs-ei#634]
**Description:**
On copying the Endpoint Template provided in the docs, the Integration Studio throws errors. This is a known issue for Integration Studio.  

**Related Issue** 
https://github.com/wso2/devstudio-tooling-ei/issues/516 

**Relevant Page** 
https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/use-cases/examples/template_examples/using-endpoint-templates.md

**Comment by nilminiwso2** [comment]
Removed the WIP banner in the docs because [1] is now fixed.

Placing the issue on hold for the remaining work:
- Write a new example use case for Endpoint Templates.

[1] https://github.com/wso2/devstudio-tooling-ei/issues/516
