### ISSUE TITLE
MI - QUICK START GUIDE

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#70]
Remaining work for the QSG:

- Update the project file attachments for the QSG [1]
- Validate (with team) the QSG's applicability to EI 7
- Text formatting and Copy editing

[1] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/quick-start-guide/quick-start-guide.md

**Comment by nilminiwso2** [comment]
Assigning @a5anka  for a review.

Please note that the same QSG for the Micro Integrator of EI650 is added to EI700 with the following updates:
- The 'Run on VM' section is added.

**Comment by a5anka** [comment]
@nilminiwso2 Do we have instruction on generating or downloading `hello-world-config-projectCompositeApplication_1.0.0.car`. I couldn't find it in the linked document.

**Comment by a5anka** [comment]
Is `curl` accessible in Windows? We might have to add a tool that can be used easily by Windows users.

**Comment by nilminiwso2** [comment]
@a5anka : regarding "Do we have instruction on generating or downloading hello-world-config-projectCompositeApplication_1.0.0.car. I couldn't find it in the linked document."

The CAR is available in the project file that we download in the 'Set up the Workspace' section. This is the MI_QSG_HOME directory.

**Comment by a5anka** [comment]
> @a5anka : regarding "Do we have instruction on generating or downloading hello-world-config-projectCompositeApplication_1.0.0.car. I couldn't find it in the linked document."
> 
> The CAR is available in the project file that we download in the 'Set up the Workspace' section. This is the MI_QSG_HOME directory.

:+1: I missed that one.
