### ISSUE TITLE
The json payloads inside tables are not rendered properly

### ISSUE THREAD

**Issue by Nirothipan** [wso2/docs-ei#717]
**Description:**

In https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/exposing-several-services-as-a-single-service/ step 16

![Screenshot from 2019-10-07 20-17-03](https://user-images.githubusercontent.com/24619763/66322272-77955e80-e93f-11e9-9bfc-6167876bf429.png)

The rendering is not correct.

The correct payload is 

```
{
"appointmentNumber":$1,
"doctor":$2,
"patient":$3,
"fee":$4,
"confirmed":"false",
"card_number":"$5"
}
```

**Comment by Nirothipan** [comment]
The step 7 in tutorial https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/using-the-gmail-connector/#update-the-message-flow also need to be updated.

it is rendered as 
![Screenshot from 2019-10-08 15-27-05](https://user-images.githubusercontent.com/24619763/66386596-1d98a580-e9e0-11e9-9205-4f904cc654e6.png)

Correct inputs

![Screenshot from 2019-10-08 15-27-46](https://user-images.githubusercontent.com/24619763/66386718-43be4580-e9e0-11e9-8309-a9f808611fbb.png)

**Comment by nilminiwso2** [comment]
Fixed.
