### ISSUE TITLE
[EI-7] MI Asynchronous messaging examples are missing config information

### ISSUE THREAD

**Issue by himasha** [wso2/docs-ei#836]
**Description:**
Under https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/jms_examples/consuming-jms/ we need to define where broker libs need to be added, and the configuration changes (enabling transport sender/listener) required.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
The examples section will be improved with the required details soon.

**Comment by nilminiwso2** [comment]
We have now linked the sample to separate pages on how to configure the broker with the Micro Integrator.
Please reopen the issue if you have questions about this.
Thanks for reporting.
