### ISSUE TITLE
[EI-7] Missing location path when adding JDBC drivers

### ISSUE THREAD

**Issue by himasha** [wso2/docs-ei#841]
**Description:**
In https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/data_integration/rdbms-data-service/ it only states the location to add JDBC drivers if embedded MI within tooling is used. Better to mention the location path when adding the JDBC drivers to a remote MI as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
We have now improved these instructions for all examples. 
Thanks for reporting.
