### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by krishnilak** [wso2/docs-ei#851]
Location : https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/saas-integrations/sfdc46/working-with-salesforce-client/1/

I am getting an error when executing the following command.
ballerina pull wso2/working_with_salesforce_client
seems like above template is not available in the ballerina central. 

Error : error: module not found: wso2/working_with_salesforce_client:*_java8 or wso2/working_with_salesforce_client:*_any

**Comment by samgnaniah** [comment]
We have fixed this now. Please reopen if you still face this issue.
