### ISSUE TITLE
Remove "Message Relay Module" section from the docs

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/docs-ei#864]
**Description:**
Since admin services are no longer support with Micro-integrator, "Message Relay Module" section should be removed in [https://ei.docs.wso2.com/en/latest/micro-integrator/setup/message_builders_formatters/message-relay/](https://ei.docs.wso2.com/en/latest/micro-integrator/setup/message_builders_formatters/message-relay/) page.

**Suggested Labels:**
Bug

**Affected Product Version:**
7.0.0 Micro-integrator

**Comment by nilminiwso2** [comment]
Doc already updated
