### ISSUE TITLE
MI - INSTALL AND SETUP section (Deployment/Clustering doc)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#88]
The clustering instructions for EI650 [1] rewritten for EI700 [2]. New toml-based configs applied.

[1] https://docs.wso2.com/display/EI650/Clustering+the+ESB+Profile
[2] https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md

related issues: 
- diagram update: https://github.com/wso2/docs-ei/issues/332
- hazelcast for deployment: https://github.com/wso2/docs-ei/issues/337

**Comment by nilminiwso2** [comment]
Doc is completed.
Review required.

**Comment by nilminiwso2** [comment]
Assigning to @Asitha for review.

This is the new deployment guide for EI7, based on toml configs:
- Hosted on netlify: https://wso2docs-configurationcatalog-3.netlify.com/setup/deployment/deploying_wso2_ei/
- https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/setup/deployment/deploying_wso2_ei.md

**Comment by nandika** [comment]
Let's update the sentence "Go to the WSO2 Micro Integrator product page and click Download to get the .pkg file. " as "Go to the WSO2 Micro Integrator product page and click Download to get the operating system specific installer.

**Comment by nilminiwso2** [comment]
done.
