### ISSUE TITLE
[Doc Site] Transparent Navigation Footer causes text look scrambled

### ISSUE THREAD

**Issue by dilee** [wso2/docs-ei#885]
**Description:**
The partially transparent navigation footer causes text look scrambled.

<img width="829" alt="Screen Shot 2019-10-17 at 13 37 50" src="https://user-images.githubusercontent.com/7193470/66992179-01cf8680-f0e7-11e9-91d3-29ca905d6e6c.png">

It would be better if we can make it opaque.

**Comment by nilminiwso2** [comment]
Duplicate issue.
Will fix this from https://github.com/wso2/docs-ei/issues/796
thanks for reporting.
