### ISSUE TITLE
Doc Feedback: Typo and inconsistent on doc page for EI-MI.

### ISSUE THREAD

**Issue by lakshikap** [wso2/docs-ei#890]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/overview/introduction/

"Graphical integration desigining" - Side link has a typo and capitalization with other links is not consistent

**Comment by nilminiwso2** [comment]
PRs:
- https://github.com/wso2/docs-ei/pull/1155
- https://github.com/wso2/docs-ei/pull/1154

Thanks for reporting
