### ISSUE TITLE
Issues in config-catalog documentation

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/docs-ei#897]
**Description:**
## Instructions for use
- This section should have a sample deployment toml file which demonstrate different aspects of toml configuration file format

## Deployment
- `hostname` does not have default value.

## Primary keystore
- `[keystore_tls]` should be renamed as `[keystore.primary]`
- `[keystore_internal]` should be renamed as `[keystore.internal]`
- `algorithm` is missing in `[truststore]` section

## HTTP/S transport (non-blocking mode)
- `socket_timeout` default value should be 180000
- `listener.wsdl_epr_prefix` no default values should assigned
- `listener.keystore.file_name` default should be `repository/resources/security/$ref{keystore.primary.file_name}`
- `listener.truststore.file_name` default should be `repository/resources/security/$ref{truststore.file_name}`
- Should be no default for `sender.proxy_host` and `sender.proxy_port`
- `sender.non_proxy_hosts` should have no default. And type should be Array instead of String.
- `sender.hostname_verifier` no default values
- `sender.keystore.file_name` default should be `repository/resources/security/$ref{keystore.primary.file_name}`
- `sender.truststore.file_name` default should be `repository/resources/security/$ref{truststore.file_name}`

### transport.blocking.http
- `listener.port` this is not mandatory to define
- `sender.enabled` not mandatory to define
- `sender.enable_client_caching`, `sender.transfer_encoding`, `sender.default_connections_per_host, `sender.omit_soap12_action`, `sender.so_timeout`  not mandatory to define
- `sender.default_connections_per_host` this should be an integer
- `sender.omit_soap12_action` this should be a boolean
- `sender.so_timeout` this should be a integer and default should be 60000

## HTTP proxy profile
- `target_hosts` This should be array of string
- `proxy_host` There should be no default values
- `bypass_hosts` type thould be array of string
- same applied for the `transport.http.secured_proxy_profile`
- `listener.keystore.file_name` default value should be`repository/resources/security/$ref{keystore.primary.file_name}`

##  SAP transport
- `listener.enabled`, `sender.enabled` this property should be removed from the doc
- `listener.idoc.enable`, `listener.bapi.enable`, `sender.idoc.enable`, `sender.bapi.enable` should be add to the doc.

## Message Mediation
- `synapse.threads.keepalive` this should be removed from the doc
- The following properties should be add to the `[mediation]` section.
```
[mediation]
synapse.command_debugger_port=9005
synapse.event_debugger_port=9006
synapse.enable_xml_nil=false
synapse.disable_auto_primitive_regex = "^-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][+-]?[0-9]+)?$"
synapse.disable_custom_replace_regex = "@@@"
synapse.enable_namespace_declaration = false
synapse.build_valid_nc_name = false
synapse.enable_auto_primitive = false
synapse.json_out_auto_array = false
inbound.core_threads = 20
inbound.max_threads = 100
```

**Comment by nilminiwso2** [comment]
Fixed.
