### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docs-ei#902]
Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/guides/correlating-events/

> Define the input stream that captures the humidity as follows. `@sink(type='log', prefix='RoomState]:') define stream StateNotificationStream(temp double, humid double);` The output directed to this stream is published via a sink of the log type. For more information about publishing data via sinks, see the Publishing Data guide.

I think the code section is wrong

**Comment by RukshiW** [comment]
This guide is removed and therefore, this is obsolete. The content of this guide is moved to [1] which has tested examples.

[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/guides/processing-data/
