### ISSUE TITLE
Doc Feedback: Difference Response in the QSG

### ISSUE THREAD

**Issue by joyrathnayake** [wso2/docs-ei#907]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/overview/quick-start-guide/

As per the QSG, we should get the response as below:
[
    [
        {
            "name": "Geln Ivan",
            "time": "05:30 PM",
            "hospital": "pineValley"
        },
        {
            "name": "Daniel Lewis",
            "time": "05:30 PM",
            "hospital": "pineValley"
        }
    ],
    [
        {
            "name": "Shane Martin",
            "time": "07:30 AM",
            "hospital": "Grand Oak"
        },
        {
            "name": "Geln Ivan",
            "time": "08:30 AM",
            "hospital": "Grand Oak"
        }
    ]
]

However, when I follow the QSG, I get the below response,
[
    [
        {
            "name": "John Mathew",
            "time": "03:30 PM",
            "hospital": "Grand Oak"
        },
        {
            "name": "Allan Silvester",
            "time": "04:30 PM",
            "hospital": "Grand Oak"
        }
    ],
    [
        {
            "name": "John Mathew",
            "time": "07:30 AM",
            "hospital": "pineValley"
        },
        {
            "name": "Roma Katherine",
            "time": "04:30 PM",
            "hospital": "pineValley"
        }
    ]
]

I tried a few times and I always get this response which is different from the QSG. What could be the reason?

**Comment by nilminiwso2** [comment]
This is corrected now.
Thanks for reporting this.
