### ISSUE TITLE
Changing keystore.file_path to keystore.location in toml transport configs

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/docs-ei#908]
**Description:**
Current keystore, truststore configurations for transport geven in the following format.
```
<Transport sender or listerner>.keystore.file_name = "repository/resources/security/$ref{keystore.primary.file_name}"
```

These configurations should be renamed into the following format.

```
<Transport sender or listerner>.keystore.location = "repository/resources/security/$ref{keystore.primary.file_name}"
```

Documentations should be also changed from `file_name` to the `location`

**Comment by nilminiwso2** [comment]
On hold until the implementation is completed.
