### ISSUE TITLE
[Micro Integrator] - Improve documents about Secure valut

### ISSUE THREAD

**Issue by Nirothipan** [wso2/docs-ei#925]
**Description:**

We need to test the following docs and apply further improvements.

- [x] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/replace_passwords_with_sys_properties/

- [x] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/injecting-parameters/

- [x] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/

**Comment by nilminiwso2** [comment]
Please refer new docs [1].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/
