### ISSUE TITLE
MI - CONFIG CATALOG (Custom Transport parameter descriptions)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-ei#97]
Config descriptions for the following toml sections:

- [[custom_transport.listener]]
- [[custom_transport.sender]]

**Comment by madushadhanushka** [comment]
Fix in https://github.com/wso2/docs-ei/pull/2567

**Comment by samgnaniah** [comment]
Review complete so closing this issue.

**Comment by samgnaniah** [comment]
Reopening this as there is more to be done here.

@nilminiwso2 please have a look.

**Comment by nilminiwso2** [comment]
updated config catalog for 7.1.0: https://github.com/wso2/docs-ei/pull/2612
