### ISSUE TITLE
Improve experience in mobile view

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-ei#992]
The main three buttons on the first page[1]  aren't clickable from the mobile view. Please check this as well as other pages for improved mobile friendly usage.

[1] - https://ei.docs.wso2.com/

**Comment by nilminiwso2** [comment]
This is no longer valid for the EI 7.1.0 release.
The problem is there in 7.0.0 though.
Shall we close this? @samgnaniah wdyt?

**Comment by samgnaniah** [comment]
+1 to close.
